### ISSUE TITLE
Issue with "XSOAR CI/CD" in @site/docs/reference/articles/xsoar-ci-cd.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#1012]
## Describe the problem
The Overview video is not working. 

## Suggested fix
Video starts correctly.

**Comment by MosheEichler** [comment]
We tested it and it works.
I have attached some pictures of the video.

![Screen Shot 2022-03-14 at 9 31 45](https://user-images.githubusercontent.com/78307768/158125031-6f40cb97-18af-4ee5-b113-568d41f56b80.png)
![Screen Shot 2022-03-14 at 9 31 51](https://user-images.githubusercontent.com/78307768/158125050-a1ce7271-dbd4-4641-86f1-29448495f48c.png)
![Screen Shot 2022-03-14 at 9 31 56](https://user-images.githubusercontent.com/78307768/158125056-281c4915-1402-49ba-9109-0546f12bff27.png)
