### ISSUE TITLE
Issue with "Active Directory Query v2" in @site/docs/reference/integrations/active-directory-query-v2.md

### ISSUE THREAD

**Issue by apekarovsky** [demisto/content-docs#1054]
## Describe the problem

* Page: [Active Directory Query v2](https://xsoar.pan.dev/docs/reference/integrations/active-directory-query-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md

1. Customer is requesting the permissions we need for each command to be documented.
We have it for : Enable/Disable an AD user account but not for all other commands.

2. If we need "Domain Admin" for all the commands to work properly , it's fine , but we need to document that in the article. Customer requested an official document that stated the "Domain Admin" permissions to be able to send to their System team ,for granting such permissions to XSAOR_User.

**Comment by glicht** [comment]
@apekarovsky please ask the customer to submit as a support request
