### ISSUE TITLE
Issue with "Test Playbooks" in @site/docs/integrations/test-playbooks.md

### ISSUE THREAD

**Issue by Ni-Knight** [demisto/content-docs#1070]
## Describe the problem
The convention for test playbooks is SomePlayBook_Test and not SomePlayBook-Test as stated here (Underscore and not a hyphen).

* Page: [Test Playbooks](https://xsoar.pan.dev/docs/integrations/test-playbooks)
* Source: https://github.com/demisto/content-docs/tree/master/docs/integrations/test-playbooks.md

## Screenshots
![image](https://user-images.githubusercontent.com/24267931/163356955-03c9da98-3daf-454f-bc8c-20811894f50f.png)

## Suggested fix
Update documentation.

**Comment by MosheEichler** [comment]
Fixed by this PR https://github.com/demisto/content-docs/pull/1072
