### ISSUE TITLE
Issue with "SplunkPy" in @site/docs/reference/integrations/splunk-py.md

### ISSUE THREAD

**Issue by krisgabor** [demisto/content-docs#108]
## Describe the problem

Typo on Cortex - spelled "Coretx" in multiple locations on the page.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
Thanks for reporting this. We will fix.
