### ISSUE TITLE
Docker container Failed error

### ISSUE THREAD

**Issue by Kakashi1499** [demisto/content-docs#1100]
Script failed to run: Docker code runner got container error: [Docker code script is in inconsistent state, expected pong but didn't got any response, exit error: Container exit with error. container name: [demistoserver_pyexec-ae9cdf1d-d970-4ef4-8684-35dd857a395c-demistopython33.9.8.24399--83] error: [exit status 1] stderr: [/usr/local/bin/python: can't find '__main__' module in '/tmp/pyrunner/_script_docker_python_loop.py'
] (2619) (2610)] (2611) (2603)

**Comment by Kakashi1499** [comment]
If export pack integration to demisto, above error displayed

**Comment by MosheEichler** [comment]
Closing the issue in `content-docs` repository
The correct repository for issues like this is the `content` repository
There is already an open issue there https://github.com/demisto/content/issues/19123
