### ISSUE TITLE
Issue with "ServiceNow v2" in @site/docs/reference/integrations/service-now-v2.md

### ISSUE THREAD

**Issue by TychoSchmidt-demisto** [demisto/content-docs#1101]
## Describe the problem

* Page: [ServiceNow v2](https://xsoar.pan.dev/docs/reference/integrations/service-now-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/ServiceNow/Integrations/ServiceNowv2/README.md

_Confirm whether you will use ServiceNow out of the box or the Security Incident Response (SIR) module, since mirroring is not supported out of the box for SIR._

According to this comment by Bar Katzir, mirroring for SNOW Security Incidents (SIR) is supported: 
https://paloaltonetworkscloud.aha.io/features/FR-580?active_tab=related

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Update the document to reflect mirroring of SIR is supported

**Comment by bakatzir** [comment]
@TychoSchmidt-demisto thx.
next rime, feel free to suggest the edit yourself, instead of reporting an issue.
