### ISSUE TITLE
Issue with "Set Up Your Dev Environment" :**ERROR: poetry is missing . Please install using: brew install.hooks**. 

### ISSUE THREAD

**Issue by kanchanDevi** [demisto/content-docs#1142]
![Screenshot 2022-07-04 020618](https://user-images.githubusercontent.com/93980703/177056434-b46b2b15-8251-4e83-be09-ee462244fe2e.png)
Hi everyone 

I am new to both Python and Xsoar. I am following the tutorial step by step to get the virtual environment in linux. I completed all the steps except running the bootstrap. It is showing me an errors\ that **ERROR: poetry is missing . Please install using: brew install.hooks**. I feel this fort is for Mac users?, I am using ubuntu app in windows and WSL.

Please help me how to resolve this or to kindly share me any windows git fork is available. Appreciate your time and help

**Comment by MosheEichler** [comment]
Hi, @kanchanDevi Thanks for asking!

To install poetry in Linux (or other OS) please see here
https://github.com/python-poetry/install.python-poetry.org
