### ISSUE TITLE
Issue with "Atlassian Jira v2" in @site/docs/reference/integrations/jira-v2.md

### ISSUE THREAD

**Issue by NullxByte** [demisto/content-docs#1191]
## Describe the problem

* Page: [Atlassian Jira v2](https://xsoar.pan.dev/docs/reference/integrations/jira-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/Jira/Integrations/JiraV2/README.md

Stale information and inaccuracy

**Problem**:  Much of the documentation regarding mirroring, classifications, and mappings are incorrect. This documentation seems to have been written for a much older version of XSOAR. Some of the main issues are the options for mirroring listed in the docs does not match the actual integration options. Our docs show the integration configuration options for External Schema Support, Can Sync Mirror In, and Can Sync Mirror Out but those options are not available in the integration any more. Also the locations of integrations and mappers is different than in the instructions. The current instructions tell the user to go to _settings -> advanced -> fields -> new field_ to create a new field but this is outdated. The current path for that option is _Settings -> Objects Setup -> Incidents -> Incident Fields_. There are multiple inaccuracies similar to this
## Environment
 - OS: N/A
 - Browser: N/A
 - Browser Version:

## Suggested fix

There are multiple updates needed to the docs, below are some of the main ones:

- Update **Configure Incident Mirroring** section to reflect current integration configuration options
- Update **Mirror In And Out Custom Fields** section to reflect the current path to the fields settings
- Need to update most of the screenshots as most of them are from much older versions of XSOAR and most of the config options have changed
- All of the sections after **Configure Incident Mirroring** need to be reviewed and updated with up to date instructions and screenshots

**Comment by MosheEichler** [comment]
Closing this issue since we opened the issue in [Jira](https://jira-hq.paloaltonetworks.local/browse/CIAC-4231)

**Comment by MosheEichler** [comment]
Closing this issue since we opened the issue in [Jira](https://jira-hq.paloaltonetworks.local/browse/CIAC-4231)
