### ISSUE TITLE
Issue with "Microsoft Teams" in @site/docs/reference/integrations/microsoft-teams.md

### ISSUE THREAD

**Issue by acicalla-ampere** [demisto/content-docs#1206]
## Describe the problem
The documentation seems to be out of date. Microsoft made a change and now there is no app studio. In the Developer portal there is no option to import the demisto bot anymore. 

* Page: [Microsoft Teams](https://xsoar.pan.dev/docs/reference/integrations/microsoft-teams)
* Source: https://github.com/demisto/content/blob/master//Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by merit-maita** [comment]
Hello @acicalla-ampere 

for the depreciation of the app studio yes its stated that its deprecated and developer portal should be used. in the developer portal there's the option to import the Demisto bot, as it could be seen in the screenshot for both of the cases, if its not what you intended, please explain more.
<img width="817" alt="app studio deprecated " src="https://user-images.githubusercontent.com/49760643/201933491-4d7e8ce8-fc53-476a-826d-f25ebcd32618.png">

<img width="839" alt="Uploading the demisto bot" src="https://user-images.githubusercontent.com/49760643/201934000-bd16d19c-417f-4cbb-9678-d1937667c1bc.png">

**Comment by merit-maita** [comment]
Hello @acicalla-ampere 
any comment or explanation?

**Comment by acicalla-ampere** [comment]
Yes, it still doesn’t work. I’ve got a support ticket open with Palo Alto currently.

Thank you,

[signature_1620578407]
Anthony Cicalla | Senior Principal IT Security Architect
C 415.937.2985|O530.745.4137 | ***@***.******@***.***>
4655 Great America Parkway, Suite 601 | Santa Clara CA 95054<webextlink://4655%20Great%20America%20Parkway,%20Suite%20601%20|%20Santa%20Clara%20CA%2095054>
Book a Meeting<https://meetings.hubspot.com/acicalla>



From: merit-maita ***@***.***>
Date: Saturday, November 19, 2022 at 1:20 PM
To: demisto/content-docs ***@***.***>
Cc: Anthony Cicalla ***@***.***>, Mention ***@***.***>
Subject: Re: [demisto/content-docs] Issue with "Microsoft Teams" in @site/docs/reference/integrations/microsoft-teams.md (Issue #1206)
[EXTERNAL EMAIL NOTICE: This email originated from an external sender. Please be mindful of safe email handling and proprietary information protection practices.]

Hello @acicalla-ampere<https://github.com/acicalla-ampere>
any comment or explanation?
