### ISSUE TITLE
Issue with "Integration Code Generator" in @site/docs/integrations/code-generator.md

### ISSUE THREAD

**Issue by K-Yo** [demisto/content-docs#1211]
## Describe the problem

* Page: [Integration Code Generator](https://xsoar.pan.dev/docs/integrations/code-generator)
* Source: https://github.com/demisto/content-docs/tree/master/docs/integrations/code-generator.md

This documentation is not complete, the values in the examples are not the same as the ones in documentation parts.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
@anara123 FYI

**Comment by ShirleyDenkberg** [comment]
@K-Yo File was updated.  See https://github.com/demisto/content-docs/blob/master/docs/integrations/code-generator.md
Closing this issue now.
