### ISSUE TITLE
Issue with "Nozomi Networks" in @site/docs/reference/integrations/nozomi-networks.md

### ISSUE THREAD

**Issue by tahimakthar** [demisto/content-docs#1222]
## Describe the problem

NOZOMI integration not fetching incident if it has added with incoming mapper.

It only works with classifier hence the context data is not shown correctly on Incident fields.

* Page: [Nozomi Networks](https://xsoar.pan.dev/docs/reference/integrations/nozomi-networks)
* Source: https://github.com/demisto/content/blob/master//Packs/NozomiNetworks/Integrations/NozomiNetworks/README.md

Request for improvement as this is not standard practice to have incident without Mapper

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Currently no fix has been found.

**Comment by tahimakthar** [comment]
![Nozomi integration output](https://user-images.githubusercontent.com/26621148/199894334-24814799-a69c-4dae-97f4-31b27f16369c.png)

**Comment by MosheEichler** [comment]
I'm cosing this issue sine this repository is for docum=entation purpose only
To report an issue with the integration plseae contact [here](https://support.paloaltonetworks.com/Support/Index)
