### ISSUE TITLE
Issue with "Demisto REST API (Deprecated)" in @site/docs/reference/integrations/demisto-rest-api.md

### ISSUE THREAD

**Issue by ali-sawyer** [demisto/content-docs#1276]
## Describe the problem

* Page: [Demisto REST API (Deprecated)](https://xsoar.pan.dev/docs/reference/integrations/demisto-rest-api)
* Source: https://github.com/demisto/content/blob/master//Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/README.md

Why does this page say the Demisto REST API is deprecated? It is not. Or at least it is not marked as such in the product or anywhere else that I've seen.

## Screenshots
![Screen Shot 2023-01-20 at 4 11 16 PM](https://user-images.githubusercontent.com/91506078/213821377-a99eb678-3bc1-4d16-a24a-4f6d89466837.png)

## Environment
 - OS: All
 - Browser: All
 - Browser Version: n/a

## Suggested fix
Remove "Deprecated" from title and remove yellow "Deprecated" banner.

**Comment by MosheEichler** [comment]
HI @ali
It became deprecated on [this](https://github.com/demisto/content/pull/23804/files#diff-a2785f55e564471679614cee1a4f16918b82d4262815dd67975018b13489f913R156) PR
