### ISSUE TITLE
Issue with "Tenable.sc" in @site/docs/reference/integrations/tenablesc.md

### ISSUE THREAD

**Issue by KentBratt** [demisto/content-docs#1290]
## Describe the problem

* Page: [Tenable.sc](https://xsoar.pan.dev/docs/reference/integrations/tenablesc)
* Source: https://github.com/demisto/content/blob/master//Packs/Tenable_sc/Integrations/Tenable_sc/README.md

Content pack is : Tenable.Sc

I believe there is a Argument that is missing from the command : tenable-sc-create-scan

It is missing the Argument : plugin_id

The integrations source code references the argument, but there is no way to input it via the task. 
Line 637 : plugin_id = demisto.args().get('plugin_id')

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Add the Argument plugin_id to the Command tenable-sc-create-scan so it can be used

**Comment by MosheEichler** [comment]
@KentBratt Please open a ticket for this.
I'm closing this issue since this is only the documentation website
