### ISSUE TITLE
Issue with "Set Up Your Remote Dev Environment" in @site/docs/tutorials/tut-setup-dev-remote.md

### ISSUE THREAD

**Issue by K-Yo** [demisto/content-docs#1299]
## Describe the problem

* Page: [Set Up Your Remote Dev Environment](https://xsoar.pan.dev/docs/tutorials/tut-setup-dev-remote)
* Source: https://github.com/demisto/content-docs/tree/master/docs/tutorials/tut-setup-dev-remote.md

an image is not shown but just the text «image»

## Screenshots

![image](https://user-images.githubusercontent.com/1626464/221645719-20943494-f8ff-4cf1-a584-bb06dd12a429.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by MosheEichler** [comment]
@ilaner Are you know what is the correct image URL?
