### ISSUE TITLE
Issue with "Gmail" in @site/docs/reference/integrations/gmail.md

### ISSUE THREAD

**Issue by PaulBartruff** [demisto/content-docs#1312]
Steps 10,11, and 13 are no longer correct.  The Graphic in step 11 is also in accurate.

1. For steps 10 and 11:

There is no longer an "edit" choice in the actions tab.  Instead one must navigate to **Google Administrator Console** -> **Security** -> **Access and data control** -> **API controls**, then select **Manage Domain Wide Delegation**.  From this window one may select **Add new** and complete the configuration using the **Client ID** from the service account created earlier and add the API Scopes noted in the step 2 of **Delegate Domain-wide Authority to Your Service Account** section of the existing documentation.

2. Step 13 is overly vague

Instead one should navigate to the **Google Service Account** -> **APIs & Services** -> **Library**, then, in the top search bar, search for **admin sdk**, select **Admin SDK API**, and click **Enable**

**Comment by julieschwartz18** [comment]
@PaulBartruff - I've assigned you to review the updates to the Gmail integration README file (based on your inputs here). Please confirm the updates are ok. Thanks!

**Comment by MosheEichler** [comment]
@PaulBartruff Any updates?

**Comment by PaulBartruff** [comment]
@MosheEichler yes, see Julies https://github.com/demisto/content/pull/25679

**Comment by julieschwartz18** [comment]
Closing this PR since the updates were made and reviewed in https://github.com/demisto/content/pull/25679
