### ISSUE TITLE
Issue with "SafeBreach" in @site/docs/reference/integrations/safe-breach.md

### ISSUE THREAD

**Issue by mchasepan** [demisto/content-docs#133]
## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by mchasepan** [comment]
![sb_small_table](https://user-images.githubusercontent.com/52938925/82588729-33bb3680-9b69-11ea-8051-c1feba188e98.png)

Mac Chrome

**Comment by glicht** [comment]
- @hod-alpert please check seems we have broken images in this page

**Comment by hod-alpert** [comment]
Specifically with **SafeBreach** there are two issues:

1. Images with wrong paths (happens in some other docs too- fixing that too)
2. Hidden HTML tables (see attached image), in my editor and in git's edotor it looks Ok and so far couldn't fix it, Any ideas?

![image](https://user-images.githubusercontent.com/41257953/82746339-356a4180-9d97-11ea-9406-1fb7c8fe4ec2.png)
![image](https://user-images.githubusercontent.com/41257953/82746349-68143a00-9d97-11ea-9ce9-91a854287807.png)

**Comment by glicht** [comment]
fixed
