### ISSUE TITLE
Issue with "Contributing" in @site/docs/contributing/contributing.md

### ISSUE THREAD

**Issue by ckaadic** [demisto/content-docs#1343]
## Describe the problem

* Page: [Contributing](https://xsoar.pan.dev/docs/contributing/contributing)
* Source: https://github.com/demisto/content-docs/tree/master/docs/contributing/contributing.md

> If you’re looking for an easy way to start contributing Content to Cortex XSOAR Marketplace, have a look at the issues labeled as [good first issue](https://github.com/demisto/content/labels/good%20first%20issue), which are low-hanging fruits.

Issues are not public anymore

## Screenshots

![image](https://github.com/demisto/content-docs/assets/48683125/f70db184-d2af-4415-b86a-72fdcf634a2c)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by ShacharKidor** [comment]
Hi @ckaadic, 
Thank you for noticing this issue. 
We are working on changing this part of the documentation - in [this PR ](https://github.com/demisto/content-docs/pull/1336).

Thanks again!
