### ISSUE TITLE
Issue with "Demisto Add-on for Splunk" in @site/docs/reference/articles/splunk-add-on.md

### ISSUE THREAD

**Issue by 7kXr** [demisto/content-docs#1398]
* Page: [Demisto Add-on for Splunk](https://xsoar.pan.dev/docs/reference/articles/splunk-add-on)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/articles/splunk-add-on.md

In the configuration section on (https://xsoar.pan.dev/docs/reference/articles/splunk-add-on): "If you would like to extend the incident creatiin request timeout, provide the desired timeout under the "Timeout Value" field. By default, timeout value is 10 seconds." there is a slight typo for "creatiin" instead of "creating".

**Comment by david-syk** [comment]
addressed in https://github.com/demisto/content-docs/pull/1410
