### ISSUE TITLE
Netskope Cortex integration needs to be updated to show RESTful APIv2 model

### ISSUE THREAD

**Issue by drwillis07** [demisto/content-docs#1399]
## Describe the problem

Netskope supports an enhanced v2 version of its RESTful interface that has more endpoints, more security, and more reliable log delivery. All new response actions are built on v2 - change risk score, create/update custom URL lists, tag applications, move users, etc. Many alert endpoints are only supported on v2: CTEP/IPS, UBA, 

## Screenshots
https://docs.netskope.com/en/netskope-help/admin-console/rest-api/rest-api-v2-overview-312207/

## Environment
All

## Suggested fix

Update the integration to use v2

**Comment by MosheEichler** [comment]
Hye @drwillis07,

Thanks for opening this issue, but since this repository is only for documentation, I am closing it.
Feel free to contact our support team via a support ticket.

Thanks again.
