### ISSUE TITLE
Issue with "O365 - Security And Compliance - Content Search v2" in @site/docs/reference/integrations/security-and-compliance-v2.md

### ISSUE THREAD

**Issue by dgriffinzero** [demisto/content-docs#1409]
## Describe the problem

* Page: [O365 - Security And Compliance - Content Search v2](https://xsoar.pan.dev/docs/reference/integrations/security-and-compliance-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
* https://xsoar.pan.dev/docs/reference/integrations/security-and-compliance-v2#o365-sc-case-hold-policy-create
* https://xsoar.pan.dev/docs/reference/integrations/security-and-compliance-v2#o365-sc-compliance-case-create

In the instructions, it states to use the Data Investigator role group.  However, the Data Investigator role group doesn't provide the necessary permissions to run any of the hold or compliance creation or deletion scripts.

Data Investigator Roles:
Communication
Compliance Search
Custodian
Data Investigation Management
Export
Preview
Review
RMS Decrypt
Search And Purge

Without the Hold and Case Management roles, it can't manage holds or manage any cases that aren't already assigned to it.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Direct admins to create a custom role group with the following roles:
Case Management
Communication
Compliance Search
Custodian
Data Investigation Management
Export
Hold
Preview
Review
RMS Decrypt
Search And Purge

The permissions issue can be validated here:
[Microsoft Learn | Roles and Role Groups for Office 365 and Microsoft Purview ](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/scc-permissions?view=o365-worldwide)

Instructions for role group are here:
[Microsoft Learn | Create a custom Microsoft Purview role group](https://learn.microsoft.com/en-us/purview/microsoft-365-compliance-center-permissions#create-a-custom-microsoft-purview-role-group)

**Comment by MosheEichler** [comment]
Fixed in [this](https://github.com/demisto/content/pull/31061) PR
