### ISSUE TITLE
Issue with "Azure Storage Table" in @site/docs/reference/integrations/azure-storage-table.md

### ISSUE THREAD

**Issue by pieroballesteros1** [demisto/content-docs#1413]
## Describe the problem

Hi, im facing a problem when using  the command !azure-storage-table-entity-query table_name="***" limit="50" page="22" in Demisto/XSOAR,
The problem start when i try to get a page 22 and above.
My table has 1613 register, so that exception should happen trying to access to page=32

I notice than in azure portal, when you scroll down in the table register, first it show 1100 register, that its the same that showing until page 21 (22*50), i dont know if its for that but might be related

* Page: [Azure Storage Table](https://xsoar.pan.dev/docs/reference/integrations/azure-storage-table)
* Source: https://github.com/demisto/content/blob/master//Packs/AzureStorageTable/Integrations/AzureStorageTable/README.md

Regards and thanks in advance!!

## Screenshots

![image](https://github.com/demisto/content-docs/assets/112068454/2eed35e6-c847-4579-b96c-07a4a6d5f90b)

**Comment by MosheEichler** [comment]
Hye @pieroballesteros1,

Thanks for opening this issue, but since this repository is only for documentation, I am closing it.
Feel free to contact our support team via a support ticket.

Thanks again.
