### ISSUE TITLE
Issue with "Armis" in @site/docs/reference/integrations/armis.md

### ISSUE THREAD

**Issue by rosenbergbd-palo** [demisto/content-docs#1439]
## Describe the problem

* Page: [Armis](https://xsoar.pan.dev/docs/reference/integrations/armis)
* Source: https://github.com/demisto/content/blob/master//Packs/Armis/Integrations/Armis/README.md

The integration URL needs to include /api/v1/  at the end of it, i.e.  https://customername.armis.com/api/v1/
Without that, the server returns a 500 Internal Server Error with no explanation. 
It would be helpful to note this someplace in the docs or in the integration help text within the settings UI, as I believe we do for other integrations.

## Screenshots

<img width="984" alt="2023-12-12_17-52-37" src="https://github.com/demisto/content-docs/assets/98436212/1c7d646f-baea-4462-a97e-39a4dbaff82a">
<img width="752" alt="2023-12-12_17-46-43" src="https://github.com/demisto/content-docs/assets/98436212/92dde9e1-61ea-486f-b70c-528cef991826">

**Comment by MosheEichler** [comment]
The issue will be fixed by [this](https://github.com/demisto/content/pull/31434) PR
