### ISSUE TITLE
Issue with "Getting Started Guide" in @site/docs/concepts/getting-started-guide.md

### ISSUE THREAD

**Issue by chem12345** [demisto/content-docs#1455]
## Describe the problem

* Page: [Getting Started Guide](https://xsoar.pan.dev/docs/concepts/getting-started-guide)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/getting-started-guide.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by MosheEichler** [comment]
@chem12345 Hey :)
What is the issue? you may forgot to explain.

**Comment by MosheEichler** [comment]
Closing do to not response
