### ISSUE TITLE
Issue with "Freshworks Freshservice" in @site/docs/reference/integrations/freshworks-freshservice.md

### ISSUE THREAD

**Issue by evgenyva** [demisto/content-docs#1502]
Dear team, 
I represent a systems integrator, our customer is using Cortex XSOAR and tried to integrate it with Freshservice ITSM. We have configured the integration from the XSOAR side following the description on the Cortex web-page. Primary purpose is that Freshservice should mirror tickets from XSOAR and back. Unfortunately this integration doesn't work as expected - tickets, present in XSOAR don't appear in Freshservice.
We have engaged Freshservice team, but they said this integration was not officially supported from their side, and they couldn't help, so they proposed to go to the Cortex team to assess this integration. Would you be able to help?
The customer is using Cortex SXOAR under the Palo Alto subscription ‘International Bank of Azerbaijan Republic JSC 57699’

* Page: [Freshworks Freshservice](https://xsoar.pan.dev/docs/reference/integrations/freshworks-freshservice)
* Source: https://github.com/demisto/content/blob/master//Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/README.md

## Screenshots

![image](https://github.com/demisto/content-docs/assets/160583531/9467b016-4931-4d83-818d-82d84d2c52fa)
![image](https://github.com/demisto/content-docs/assets/160583531/9037b7df-170f-49c0-9965-c13d0cba5bbc)
![image](https://github.com/demisto/content-docs/assets/160583531/3d2b6361-72a1-4ca6-9dec-16a5cedf2882)
![image](https://github.com/demisto/content-docs/assets/160583531/c32aac77-0983-4d2a-be01-b49bf9c24c96)
![image](https://github.com/demisto/content-docs/assets/160583531/fb1c7dd9-370d-4422-8648-f94fd51ef16d)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by JudahSchwartz** [comment]
@evgenyva hey sorry for the late response here. Please ask the customer to open a ticket with XSOAR support directly. This repository is just for xsoar documentation.

**Comment by evgenyva** [comment]
Hi, Judah.

OK, we've done  it already. Thanks.


Best Regards,

Evgeny Vasilyev

ITSM/ITAM Business Development Manager, CIS&APAC

***@***.***

[signatureImage]
________________________________
