### ISSUE TITLE
Issue with "ServiceNow v2" in @site/docs/reference/integrations/service-now-v2.md

### ISSUE THREAD

**Issue by dev63198** [demisto/content-docs#1541]
## Describe the problem

* Page: [ServiceNow v2](https://xsoar.pan.dev/docs/reference/integrations/service-now-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/ServiceNow/Integrations/ServiceNowv2/README.md

False information provided on the page. 
it is not true what XSOAR documentation says that web_service_admin and/or rest_api_explorer role(s) is required to make API calls. https://xsoar.pan.dev/docs/reference/integrations/service-now-v2#required-permissions

## Environment
 - OS: N/A 
 - Browser: any
 - Browser Version: any
 - ServiceNow version: Utah (or later)

## Suggested fix

Update the documentation.
Ability to call web services in ServiceNow is granted by role snc_platform_rest_api_access. (an old, deprecated variant for this is rest_service )
ServiceNow documentation: https://docs.servicenow.com/bundle/utah-platform-administration/page/administer/roles/reference/r_BaseSystemRoles.html#d115631e4361

**Comment by ShirleyDenkberg** [comment]
Document updated. https://xsoar.pan.dev/docs/reference/integrations/service-now-v2#required-permissions
