### ISSUE TITLE
Issue with "National Vulnerability Database Feed v2" in @site/docs/reference/integrations/feed-nv-dv2.md

### ISSUE THREAD

**Issue by edibleShell** [demisto/content-docs#1552]
## Describe the problem

* Page: [National Vulnerability Database Feed v2](https://xsoar.pan.dev/docs/reference/integrations/feed-nv-dv2)
* Source: https://github.com/demisto/content/blob/master//Packs/FeedNVDv2/Integrations/FeedNVDv2/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

The Base command !nvd-get-indicators has an incorrect argument value passed to it. The current value is history=90. When executed as written in the Playground you receive the following error. 

** date_range must be "number date_range_unit", examples: (2 hours, 4 minutes,6 months, 1 day, etc.) **

I recommend updating the markdown to include  !nvd-get-indicators history="90 days" and update the Input description to include these specific units of time.

**Comment by ShirleyDenkberg** [comment]
@dorschw I think this ticket should be assigned to you.

**Comment by dorschw** [comment]
tracked internally as [CIAC-10592](https://jira-dc.paloaltonetworks.com/browse/CIAC-10592)

**Comment by ShirleyDenkberg** [comment]
Closed by Merge.
