### ISSUE TITLE
Issue with "Generic Export Indicators Service" in @site/docs/reference/integrations/edl.md

### ISSUE THREAD

**Issue by JPNieuwendam** [demisto/content-docs#1554]
## Describe the problem

* Page: [Generic Export Indicators Service](https://xsoar.pan.dev/docs/reference/integrations/edl)
* Source: https://github.com/demisto/content/blob/master//Packs/EDL/Integrations/EDL/README.md

The document does not make clear what the steps for accessing the EDL are from the HTTPS service when hosted. There is a link that says it contains the instructions, but it links to the same page. It is not clear once the integration instance has been set up how the customer can log in and access the EDL from their env. Please also clarify when Creds are required for hosted vs engine

## Screenshots
![image](https://github.com/demisto/content-docs/assets/102976149/4ed3e083-9740-46e2-843c-812ceda92874)

## Environment
 - OS: Mac
 - Browser: chrome
 - Browser Version: latest

## Suggested fix

Clarify the URL syntax needed. Both Https://ext-<server>/ and https://edl-<server> Is one used for the engine vs the other?

**Comment by ShirleyDenkberg** [comment]
@ShahafBenYakir Can you provide the information needed for this ticket?

**Comment by ShahafBenYakir** [comment]
@JPNieuwendam Are you running this in XSOAR 6, XSOAR 8 or XSIAM?

**Comment by ShahafBenYakir** [comment]
Closing as no response is given.
@JPNieuwendam You can reopen when you have answers to the above questions.
