### ISSUE TITLE
Issue with "TimeComponents" in @site/docs/reference/scripts/time-components.md

### ISSUE THREAD

**Issue by ArpanC-L** [demisto/content-docs#1556]
## Describe the problem

* Page: [TimeComponents](https://xsoar.pan.dev/docs/reference/scripts/time-components)
* Source: https://github.com/demisto/content/blob/master//Packs/FiltersAndTransformers/Scripts/TimeComponents/README.md

 Typo

The link of python dateparser used in section https://xsoar.pan.dev/docs/reference/scripts/time-components#inputs is a typo. Mentioned link is [https://dateparser.readthedocs.io/en/latest/\#popular-formats](https://dateparser.readthedocs.io/en/latest/%5C#popular-formats), which is not working.

## Screenshots

![Linkissue-1](https://github.com/demisto/content-docs/assets/169807233/5a12971b-60b0-44f0-8265-95cc8d70f70b)
![Linkissue-2](https://github.com/demisto/content-docs/assets/169807233/4b639ea4-847b-4e5a-9277-d770cf10d87f)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Actual link should be https://dateparser.readthedocs.io/en/latest/#popular-formats

**Comment by ShirleyDenkberg** [comment]
This issue has been fixed by https://github.com/demisto/content/pull/34554.
