### ISSUE TITLE
just installed xsoar and can t execute scripts

### ISSUE THREAD

**Issue by yasser-bk52** [demisto/content-docs#1557]
DBot
May 28, 2024 3:15 PM
Scripts returned an errorHide reason
Command:
 
!HelloWorldScript
Hide reason
Reason
Error from Scripts is : Script failed to run: Docker code runner got container error: [Docker code script is in inconsistent state, expected pong but didn't got any response, exit error: Container exit with error. container name: [demistoserver_pyexec-fd38c677-95ad-45b2-8985-96f46baac26d-demistopython33.10.13.83255--57] error: [exit status 1] stderr: [/usr/local/bin/python: can't find '__main__' module in '/tmp/pyrunner/_script_docker_python_loop.py'
] (2619) (2610)] (2611) (2603)

**Comment by richardbluestone** [comment]
@yasser-bk52 Please open a CS ticket at https://support.paloaltonetworks.com
