### ISSUE TITLE
Issue with "NIST - Lessons Learned" in @site/docs/reference/playbooks/nist---lessons-learned2.md

### ISSUE THREAD

**Issue by mcvic1rj** [demisto/content-docs#1563]
## Describe the problem

* Page: [NIST - Lessons Learned](https://xsoar.pan.dev/docs/reference/playbooks/nist---lessons-learned2)
* Source: https://github.com/demisto/content/blob/master//Packs/NIST/Playbooks/playbook-NIST_-_Lessons_Learned_README.md

The playbook screenshot included is not of the lessons learned playbook. It is of the access investigation playbook.

## Screenshots
N/A
## Environment
N/A

## Suggested fix
Update playbook image to be one of the correct playbook.

**Comment by ShirleyDenkberg** [comment]
@OmriItzhak Please update the file with the lessons learned playbook.

**Comment by ShirleyDenkberg** [comment]
File has been updated with the Lessons Learned playbook screenshot.  https://xsoar.pan.dev/docs/reference/playbooks/nist---lessons-learned2
