### ISSUE TITLE
Issue with "ExportAuditLogsToFile" in @site/docs/reference/scripts/export-audit-logs-to-file.md

### ISSUE THREAD

**Issue by hotfoxzuso** [demisto/content-docs#1575]
## Describe the problem
When I try to use !exportauditlogs in XSOAR Playgroup.
It's not work and show error message.
"
Reason
Error from Scripts is : Script failed to run: 
Error: [Traceback (most recent call last):
   
   File "<string>", line 128, in <module>
   File "<string>", line 90, in main
 KeyError: 'request_data'
] (2604) (2603)
"

## Screenshots
![image](https://github.com/demisto/content-docs/assets/28667552/86eb8236-347d-410d-b9dd-d665ec113826)

## Environment
 - OS: Ubuntu
 - Browser: Chrome
 - Browser Version: 126.0.6478.127 

## Suggested fix
Help Fix it.

**Comment by ShirleyDenkberg** [comment]
@michal-dagan Should this be assigned to you?

**Comment by MosheEichler** [comment]
Hey @hotfoxzuso 
Moved [internally](https://jira-dc.paloaltonetworks.com/browse/CIAC-11072) thank you for your update.
