### ISSUE TITLE
Issue with "SetGridField" in @site/docs/reference/scripts/set-grid-field.md

### ISSUE THREAD

**Issue by apekarovsky** [demisto/content-docs#158]
## Describe the problem

No grid examples pictures

## Screenshots

<img width="917" alt="Screen Shot 2020-06-07 at 13 41 46" src="https://user-images.githubusercontent.com/63284546/83966738-bc093d80-a8c4-11ea-89b5-7b618cc796b5.png">

## Environment
 - OS: MAC
 - Browser: Chrome
 - Browser Version: Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by glicht** [comment]
Thanks for reporting this @apekarovsky . Will be fixed soon.
