### ISSUE TITLE
Issue with "Atlassian Jira v3" in @site/docs/reference/integrations/jira-v3.md

### ISSUE THREAD

**Issue by edibleShell** [demisto/content-docs#1590]
## Describe the problem

* Page: [Atlassian Jira v3](https://xsoar.pan.dev/docs/reference/integrations/jira-v3)
* Source: https://github.com/demisto/content/blob/master//Packs/Jira/Integrations/JiraV3/README.md

Yes

Command jira-create-issue and jira-edit-issue argument issue_json contains a link that presents the user with a 404 https://developer.atlassian.com/server/jira/platform/jira-rest-api-example-create-issue-7897248/'

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix
This link might be what the previous link was referencing
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post

**Comment by ShirleyDenkberg** [comment]
@edibleShell Link seems to be working for me.  Please check again.

**Comment by edibleShell** [comment]
I can get to it now. We can close this issue.
