### ISSUE TITLE
Issue with "SlackBlockBuilder" in @site/docs/reference/scripts/slack-block-builder.md

### ISSUE THREAD

**Issue by sachinI-metron** [demisto/content-docs#1592]
## Describe the problem
We have a playbook and that playbook contains 3 tasks

1. SlackBlockBuilder  -> Send notification to slack
2. GetSlackBlockBuilderResponse  -> Get user response and set it to context data
3. ParseSlackBlockBuilderResponse  -> parse slack blocks

![image](https://github.com/user-attachments/assets/c7c3a1e1-f3f5-4a37-952e-79a98c29beba)

#Issue01:-
we successfully able to send slack notifications but most of the time we are not able to get the response back on xsoar

#Issue02:-
we are trying to send 100 slack notifications via incident,  we are able to get all notifications on slack but not able to get the response back on xsoar

* Page: [SlackBlockBuilder](https://xsoar.pan.dev/docs/reference/scripts/slack-block-builder)
* Source: https://github.com/demisto/content/blob/master//Packs/Slack/Scripts/SlackBlockBuilder/README.md

## Environment
 - OS: Linux
 - Browser: Firefox
 - Browser Version: 128.0.3 (64-bit)

**Comment by MosheEichler** [comment]
Hey @sachinI-metron 
I'm closing this issue since this repository is only for documentation. If you have problems with the playbook, please open a support ticket.

**Comment by sachinI-metron** [comment]
Hi @MosheEichler 
Thank you for the reply
Could you please tell me where I can create the support ticket?
Thanks

**Comment by MosheEichler** [comment]
Hey @sachinI-metron 
Please reach the support team here https://support.paloaltonetworks.com/Support/Index
