### ISSUE TITLE
Issue with "Development Guide" in @site/docs/dev-guide.mdx

### ISSUE THREAD

**Issue by sserrata** [demisto/content-docs#16]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The "Architecture Basics" links are broken.

## Suggested fix

Current URL: https://demisto-content-docs.netlify.com/docs/en/dev-architecture
Suggested URL: https://demisto-content-docs.netlify.com/docs/dev-architecture

**Comment by glicht** [comment]
@fvigo I think we can get rid of this page. I am not sure it is relevant for dev docs (it was copied from the main demisto site if I am not mistaken).

**Comment by fvigo** [comment]
Agreed, I'll get rid of it. Once we commit the PR I'll do a full review/cleanup of all the existing content

**Comment by fvigo** [comment]
PR #22 fixes this
