### ISSUE TITLE
Issue with "O365 Outlook Mail (Using Graph API)" in @site/docs/reference/integrations/microsoft-graph-mail.md

### ISSUE THREAD

**Issue by edibleShell** [demisto/content-docs#1607]
## Describe the problem

* Page: [O365 Outlook Mail (Using Graph API)](https://xsoar.pan.dev/docs/reference/integrations/microsoft-graph-mail)
* Source: https://github.com/demisto/content/blob/master//Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md

The send-mail argument **importance** states it has a default value of normal when the default value is set to low in the integration settings. This is setting customers email notification priority to low which means data-collection tasks and other emails from the instance might be ignored. 

Seen in Microsoft Graph Mail 1.6.14 1244506

typo in default integration settings value. 

## Screenshots

![image](https://github.com/user-attachments/assets/7d0814fd-1805-40c1-ab3d-88ec3eeb0fab)

## Environment
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 127.0.6533.120 (Official Build) (arm64)

## Suggested fix

Update the default integration settings for the importance argument to be normal instead of low.

**Comment by ShirleyDenkberg** [comment]
@nkanon Who should be assigned to this?

**Comment by meital-aizen** [comment]
> Hi @meital-aizen can you suggest what should be the default value of email importance? Thanks!

@altmannyarden @AdiPeret Can you please advise?
