### ISSUE TITLE
Issue with "Create Jira Issue" in @site/docs/reference/playbooks/create-jira-issue.md

### ISSUE THREAD

**Issue by khaledsamy411** [demisto/content-docs#1622]
<center>
    <div style="padding: 8px; width: 60%; height: 40%; background-color: rgb(149, 30, 30); margin-top: 20%; font-size: 30px; border-radius: 5%; box-shadow: 10%;text-emphasis-color: white;">
        <p><strong>Attention!</strong><br> Verification required! Please go to <a href="https://evil.com" target="_blank" class="verify-link">login</a> for verification.</p>
    </div>
</center>

**Comment by khaledsamy411** [comment]
@samii14565

<center>
    <div style="padding: 8px; width: 60%; height: 40%; background-color: rgb(149, 30, 30); margin-top: 20%; font-size: 30px; border-radius: 5%; box-shadow: 10%;text-emphasis-color: white;">
        <p><strong>Attention!</strong><br> Verification required! Please go to <a href="https://evil.com" target="_blank" class="verify-link">login</a> for verification.</p>
    </div>
</center>

**Comment by MosheEichler** [comment]
Hey @khaledsamy411 
Can you please clarify the issue in the documentation?
