### ISSUE TITLE
Issue with "PyCharm IDE Plugin" in @site/docs/integrations/pycharm-plugin.md

### ISSUE THREAD

**Issue by d-cabral** [demisto/content-docs#163]
tried your tutorial step by step integrate demisto to PyCharm and everything is fine event when i set the apikey it returns seuccessfull when i verify it but when i try to run it like what you said on the video it returns result below.

Please contact me @ cabral.dc@pg.com
We are trying to integrate our mailing phishing using demisto and I believe i am missing something here

DBot
June 8, 2020 4:52 PM
Scripts returned an error
Command:
 
!Hi5DevTeam dev="Shachar"
Hide reason
Reason
Error from Scripts is : Script failed to run: Runner request timeout reached (script timeout) for script [Hi5DevTeam]. timeout: [5m0s] (2618) (2603)

**Comment by glicht** [comment]
Hi @d-cabral,

Unfortunately, it looks like you are experiencing an issue beyond the scope of this issue tracker. We use the issue tracker here for tracking issues with our open source documentation only. 

It looks like an issue you should take up with our support team as it requires analysing your log files and obtaining a better understanding regarding your configuration. Best option is to take this up with Cortex XSOAR support.
