### ISSUE TITLE
Issue with "Arcsight - Get events related to the Case" in @site/docs/reference/playbooks/arcsight---get-events-related-to-the-case.md

### ISSUE THREAD

**Issue by kishanpise** [demisto/content-docs#1633]
Getting 404 error while adding entries in active list of arcsight using cmd as-add-entries using active list resource id.. And as checked the xsoar resource id is matching with arcsight resource id... But still issue persits.

**Comment by ShirleyDenkberg** [comment]
@nkanon @ShahafBenYakir Who should be assigned to this PR?

**Comment by ShahafBenYakir** [comment]
Hi @kishanpise This repo holds the XSOAR content documentation, issues raised here should reference problems within the aforementioned documentation. looking at your comment it sounds like you are experiencing issues with the **as-add-entries** command, to receive the best support for your problem, you need to work with the relevant PANW support to create the appropriate support ticket.
