### ISSUE TITLE
Issue with "Set Up Your Dev Environment" in @site/docs/tutorials/tut-setup-dev.md

### ISSUE THREAD

**Issue by schakradari** [demisto/content-docs#1637]
## Describe the problem

We are trying to run the precommit command like below. This command always throws SSL Verification error.

 demisto-sdk pre-commit -i Packs/CSCDomainManager/Integrations/CSCDomainManager

## Screenshots
![Error1](https://github.com/user-attachments/assets/1ff9f05d-cf6d-499f-9e38-827096484cf7)
![Error2](https://github.com/user-attachments/assets/0d73640f-715f-4d63-8c2a-7263f66d74ef)

## Environment
 - OS: [e.g. Windows]

**Comment by ShirleyDenkberg** [comment]
@nkanon Who should be assigned to this PR?

**Comment by MosheEichler** [comment]
Hi @schakradari  This repo holds the XSOAR content documentation, issues raised here should reference problems within the aforementioned documentation. looking at your comment it sounds like you are experiencing issues with demisto-sdk command, to receive the best support for your problem, you need to work with the relevant PANW support to create the appropriate support ticket.

**Comment by schakradari** [comment]
@MosheEichler , How can I get the PANW support?

**Comment by MosheEichler** [comment]
> @MosheEichler , How can I get the PANW support?

https://support.paloaltonetworks.com/Support/Index
