### ISSUE TITLE
Issue with "CrowdStrike Falcon" in @site/docs/reference/integrations/crowdstrike-falcon.md

### ISSUE THREAD

**Issue by tsachzim** [demisto/content-docs#1648]
## Describe the problem

* Page: [CrowdStrike Falcon](https://xsoar.pan.dev/docs/reference/integrations/crowdstrike-falcon)
* Source: https://github.com/demisto/content/blob/master//Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md

While using the  command "cs-falcon-resolve-incident"
with the argument: add_comment
Users asking to add the description that the comment is limited to 1024 characters.

API returns this error:

```
Error in API call to CrowdStrike Falcon: code: 400 - reason: Bad Request
invalid action value specified. must be less than 1024
```

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by ShirleyDenkberg** [comment]
Created this PR for the update -  https://github.com/demisto/content/pull/37035.  Asked @RosenbergYehuda to approve the PR.

**Comment by ShirleyDenkberg** [comment]
Doc has been updated as requested. https://xsoar.pan.dev/docs/reference/integrations/crowdstrike-falcon
