### ISSUE TITLE
Issue with "TAXII Feed" in @site/docs/reference/integrations/taxii-feed.md 

### ISSUE THREAD

**Issue by SecOpsSoar** [demisto/content-docs#1654]
## Describe the problem
[Taac](http://hailataxii.com/taxii-discovery-service) is no longer there.

* Page: [TAXII Feed](https://xsoar.pan.dev/docs/reference/integrations/taxii-feed)
* Source: https://github.com/demisto/content/blob/master//Packs/FeedTAXII/Integrations/FeedTAXII/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by MosheEichler** [comment]
Fixed by [this](https://github.com/demisto/content/pull/37200) PR
