### ISSUE TITLE
Issue with "SlackBlockBuilder" in @site/docs/reference/scripts/slack-block-builder.md 

### ISSUE THREAD

**Issue by BarHalifa** [demisto/content-docs#1658]
When I run command, it's work great.
When I run from playbook im getting:
Failed to execute SlackBlockBuilder. Error: The request to the Slack API failed. (url: https://slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'invalid_blocks_format'}

## Screenshots
From Playbook:
![image](https://github.com/user-attachments/assets/c337c30b-3aa1-4f0c-a69a-339868e299a8)

From command in playground:
![image](https://github.com/user-attachments/assets/32b87cb8-7bad-436d-8724-c45506824451)

**Comment by ShirleyDenkberg** [comment]
@nkanon Who should be assigned to this ticket?

**Comment by nkanon** [comment]
Hi @BarHalifa, this should be opened as a bug through the support portal.
This issue will be closed as it is only served for documentation purposes. 
Thanks
