### ISSUE TITLE
demisto-sdk command line argument does not exists

### ISSUE THREAD

**Issue by gachdavit** [demisto/content-docs#171]
Hi, everyone.

I am reading documentation at [this link](https://xsoar.pan.dev/docs/tutorials/tut-setup-dev). There is one step, where I should run 
```bash 
demisto-sdk lint
``` 
command on the folder Packs/HelloWorld/Integrations/HelloWorld using ```-d``` option.

Command:
```bash
demisto-sdk lint -d /path/to/demisto/content/Packs/HelloWorld/Integrations/HelloWorld/
```
Command result:
```bash
Usage: demisto-sdk lint [OPTIONS]

Error: no such option: -d
```
But, when I run command with ```-i``` argument, everything works fine.

```bash
demisto-sdk lint -i /path/to/demisto/content/Packs/HelloWorld/Integrations/HelloWorld/
```

Maybe something changes, and requires documentation update ?

I am using ```python 3.8.3``` and ```demisto_sdk 1.1.2```.

Thanks.

**Comment by Itay4** [comment]
@gachdavit thanks for reporting this
this doc indeed requires an update, we will take care of it
