### ISSUE TITLE
Issue with "Microsoft Management Activity API (O365 Azure Events)" in @site/docs/reference/integrations/microsoft-management-activity-api-o365-azure-events.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#187]
## Describe the problem

In Authentication section, the link is wrong: https://xsoar.pan.dev/docs/reference/integrations/microsoft-management-activity-api-(O365/Azure-Events)

## Suggested fix
Not sure where the link shall point.

**Comment by glicht** [comment]
@sylvainmeras thanks for reporting. It looks like the section was added by mistake. We will fix.
