### ISSUE TITLE
Issue with "Cortex Data Lake" in @site/docs/reference/integrations/cortex-data-lake.md

### ISSUE THREAD

**Issue by mikejrizzo** [demisto/content-docs#188]
## Describe the problem
Backticks in example command syntax for !cdl-query-logs get rendered as markdown styling elements when viewed in the browser and do not come through when copying/pasting text to another window.  This causes the requirement of backticks in the query to be unclear in the documentation.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix
Escape the backticks in the example SQL syntax for the cdl-query-logs command so they are visible in the browser.

**Comment by Itay4** [comment]
@mikejrizzo thanks for reporting this

not sure I understand the issue, this is how i see it:
![image](https://user-images.githubusercontent.com/31018228/86440007-5d43b200-bd12-11ea-8364-d713c767bfbc.png)

which seems fine to me

also, i can copy and paste it as expected

can you please clarify whats wrong here?

**Comment by Itay4** [comment]
@mikejrizzo thanks for reporting this, we will fix it
