### ISSUE TITLE
Issue with "SetMultipleValues" in @site/docs/reference/scripts/set-multiple-values.md

### ISSUE THREAD

**Issue by aneeshamore** [demisto/content-docs#227]
## Describe the problem

* Page: [SetMultipleValues](https://xsoar.pan.dev/docs/reference/scripts/set-multiple-values)
* Source: https://github.com/demisto/content/blob/master//Packs/CommonScripts/Scripts/script-SetMultipleValues_README.md

Customer mentioned they would like a simple example of this script and the purpose of it. 

## Suggested fix
Here's what I provided them:

`!SetMultipleValues parent=test_parent keys=key1,key2,key3 values=val1,valu2,val3`

![Screen Shot 2020-07-24 at 11 26 53 AM](https://user-images.githubusercontent.com/25312145/88423600-dd54b900-cda0-11ea-89f4-83981367659a.png)

**Comment by glicht** [comment]
@aneeshamore a PR has been created with your suggestion at: https://github.com/demisto/content/pull/8410
