### ISSUE TITLE
Issue with "VirusTotal - Private API" in @site/docs/reference/integrations/virus-total---private-api.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#228]
## Describe the problem

* Page: [VirusTotal - Private API](https://xsoar.pan.dev/docs/reference/integrations/virus-total---private-api)
* Source: https://github.com/demisto/content/blob/master//Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/README.md

The parameter " Do not use by default " is not documented.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Please explain the purpose of this setting and its effect(s).

**Comment by glicht** [comment]
Hi @sylvainmeras, Thanks for reporting this. 

The parameter is generic for all Integrations. When checked it excludes the integration instance when running a generic command that uses all available integrations such as `!file`. 

We have this documented in our main documentation site under Feed Integrations:

https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-0/cortex-xsoar-threat-intel-management-guide/threat-intelligence-feeds/feed-integrations

We will evaluate how to improve this information for all integrations. 

@kirbles19 FYI
