### ISSUE TITLE
Layout issue on PR

### ISSUE THREAD

**Issue by fvigo** [demisto/content-docs#23]
On the deployment of #22  @mchasepan sees this on his system:
![image](https://user-images.githubusercontent.com/7642165/71367757-49bad000-25a6-11ea-9e6e-1add02715051.png)

It should show "Automate the future" <BR> "with Demisto". Also the links on top should not return carriage.

@sserrata  @csestito  could you please have a look?

Thanks!

**Comment by jtschichold** [comment]
@fvigo  I don't have access to your repo, but this will fix:

```
diff --git a/src/css/custom.css b/src/css/custom.css
index 601ecb1..7ad3153 100755
--- a/src/css/custom.css
+++ b/src/css/custom.css
@@ -140,3 +140,21 @@ blockquote {
 .customer-inner > a {
   color: #333333;
 }
+
+/* XXX probably not the cleanest way */
+/* this to avoid NavBar items to wrap */
+.navbar a.navbar__link {
+  white-space: nowrap;
+}
+
+/* the NavBar is too wide for 1024px screens */
+/* we need to override the default 996px media query */
+/* with a 1279px */
+@media (max-width: 1279px) {
+  .navbar .navbar__item {
+    display: none !important;
+  }
+  .navbar .navbar__toggle {
+    display: inherit !important;
+  }
+}
```

**Comment by fvigo** [comment]
Thanks @jtschichold , the final code change was:
+/* XXX probably not the cleanest way */
+/* this to avoid NavBar items to wrap */
+.navbar a.navbar__link {
+  white-space: nowrap;
+}
+
+/* the NavBar is too wide for 1024px screens */
+/* we need to override the default 996px media query */
+/* with a 1279px */
+@media (max-width: 1279px) {
+  .navbar .navbar__item {
+    display: none !important;
+  }
+  .navbar .navbar__toggle {
+    display: inherit !important;
+  }
+  .navbar .navbar-sidebar {
+    display: block !important;
+  }
+}
