### ISSUE TITLE
Issue with "Python Code Conventions" in @site/docs/integrations/code-conventions.md

### ISSUE THREAD

**Issue by mhouston007** [demisto/content-docs#234]
## Describe the problem

* Page: [Python Code Conventions](https://xsoar.pan.dev/docs/integrations/code-conventions)
* Source: https://github.com/demisto/content-docs/tree/master/docs/integrations/code-conventions.md

Stale / incorrect information

Under the documentation for the `CommandResults` section, the parameter for the human readable content is incorrect

## Screenshots

![image](https://user-images.githubusercontent.com/58996090/88726867-7b77b480-d0fc-11ea-8a8b-8964d2746d88.png)

## Environment
 - OS: Windows
 - Browser: Chrome

## Suggested fix

Change from `human_readable` to `readable_output`

**Comment by glicht** [comment]
@anara123 FYI
