### ISSUE TITLE
Issue with "Create a Conditional Task" in @site/docs/playbooks/playbooks-create-conditional-task.md

### ISSUE THREAD

**Issue by krisgabor** [demisto/content-docs#249]
## Describe the problem

* Page: [Create a Conditional Task](https://xsoar.pan.dev/docs/playbooks/playbooks-create-conditional-task)
* Source: https://github.com/demisto/content-docs/tree/master/docs/playbooks/playbooks-create-conditional-task.md

Typo in the very last link on the page: "Playboook"

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
Thanks for reporting this. Will be fixed.
