### ISSUE TITLE
Issue with "is/is not" due to Python 2/3 versions incompatibility  in @site/docs/tutorials/tut-integration-ui.md

### ISSUE THREAD

**Issue by prostopasta** [demisto/content-docs#253]
## Describe the problem

Yoda Speak integration code written with Python 2.x and produce errors when running within the newer Python 3.x oriented versions of Cortex XSOAR 5.5+

Suggest either at least mention that code have to be run under Python 2.x 
Or as a best solution to provide the code for Python 3.x versions as well by substituting (is -> ==) and (is not -> !=)

## Suggested fix

I could provide PR by adding separate sections for Python 2 and 3 code correspondingly.

**Comment by Itay4** [comment]
hi @prostopasta 
thanks for opening this issue
the code needs to be compatible with the Python version used in the [docker image](https://xsoar.pan.dev/docs/integrations/docker#docker-images) the integration runs with, and for all new integrations/scripts we use Python 3
we are aware that the Yoda video is outdated, and we have a new one planned on our roadmap
in the mean time, you can look at our [Python Code Conventions](https://xsoar.pan.dev/docs/integrations/code-conventions) for Python 3 syntax we use
