### ISSUE TITLE
Issue with "SplunkPy" in @site/docs/reference/integrations/splunk-py.md

### ISSUE THREAD

**Issue by K-Yo** [demisto/content-docs#274]
## Describe the problem

* Page: [SplunkPy](https://xsoar.pan.dev/docs/reference/integrations/splunk-py)
* Source: https://github.com/demisto/content/blob/master//Packs/SplunkPy/Integrations/SplunkPy/README.md

Several commands are not documented at all, including all the commands starting with `splunk-kv-store`

## Environment
 - OS: any
 - Browser: any
 - Browser Version: any

## Suggested fix

Write the documentation

**Comment by glicht** [comment]
@K-Yo thanks for reporting this. We will follow and see how this doc can be improved.

**Comment by glicht** [comment]
Document has been updated.
