### ISSUE TITLE
Issue with "Azure Sentinel (Beta)" in @site/docs/reference/integrations/azure-sentinel.md

### ISSUE THREAD

**Issue by iwafula025** [demisto/content-docs#279]
## Describe the problem

* Page: [Azure Sentinel (Beta)](https://xsoar.pan.dev/docs/reference/integrations/azure-sentinel)
* Source: https://github.com/demisto/content/blob/master//Packs/AzureSentinel/Integrations/AzureSentinel/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by iwafula025** [comment]
Hi thanks for sharing the steps, however-the application registration ones (self-deployed configuration) do not work. Also, the "Test" button after configuring the integration on the Demisto side responds with an error. However, when using the !azure-sentinel-test it does confirm success. It would also be helpful to provide steps on how to set up the OVA on popular public clouds such as Azure , AWS & GCP

**Comment by glicht** [comment]
Hi @iwafula025, thanks for opening the issue. We will try to investigate and review on our side if there are any gaps. However, we won't be able to address sepcific support cases via this issue tracker. It is meant exclusively for documentation issues.  I suggest you follow with our support team. Also please check our DFIR Community: https://www.demisto.com/community/ .
