### ISSUE TITLE
Issue with "HashiCorp Vault" in @site/docs/reference/integrations/hashi-corp-vault.md

### ISSUE THREAD

**Issue by KyleZevenbergen** [demisto/content-docs#286]
The manage credentials link at the top of the doc points to the old docs.  We need to point here:
https://xsoar.pan.dev/docs/reference/articles/managing-credentials

## Describe the problem

* Page: [HashiCorp Vault](https://xsoar.pan.dev/docs/reference/integrations/hashi-corp-vault)
* Source: https://github.com/demisto/content/blob/master//Packs/HashiCorp-Vault/Integrations/integration-HashiCorp-Vault_README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by Itay4** [comment]
thanks for reporting this @KyleZevenbergen 
it was already reported in https://github.com/demisto/content-docs/issues/283 and will be tracked there
