### ISSUE TITLE
Issue with "Cortex XSOAR Concepts" in @site/docs/concepts/concepts.md

### ISSUE THREAD

**Issue by markc-dsoft** [demisto/content-docs#294]
## Describe the problem

Under Commands-external commands, there is a word, "repuration".  I think you mean reputation

* Page: [Cortex XSOAR Concepts](https://xsoar.pan.dev/docs/concepts/concepts)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/concepts.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by fvigo** [comment]
Thanks, this has been fixed!
