### ISSUE TITLE
Issue with "Welcome" in @site/docs/welcome.md

### ISSUE THREAD

**Issue by markc-dsoft** [demisto/content-docs#295]
## Describe the problem

In the Incidents section, there is a word, "incdients".  It should probably be 'incidents'

* Page: [Welcome](https://xsoar.pan.dev/docs/welcome)
* Source: https://github.com/demisto/content-docs/tree/master/docs/welcome.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
@markc-dsoft thanks for reporting this. Will be fixed.

**Comment by fvigo** [comment]
Thanks, this has been fixed!
