### ISSUE TITLE
Issue with "Microsoft Graph Security" in @site/docs/reference/integrations/microsoft-graph.md

### ISSUE THREAD

**Issue by ryanspletzer** [demisto/content-docs#296]
## Describe the problem

* Page: [Microsoft Graph Security](https://xsoar.pan.dev/docs/reference/integrations/microsoft-graph)
* Source: https://github.com/demisto/content/blob/master//Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md

Directory.ReadWrite.All application permission for Microsoft Graph basically grants the application "God Mode" privileges on Azure AD and this certainly should not be needed, or if it is needed there should be really good justification as to why it is needed and other lesser privileged permissions can't be utilized instead to follow a least privileged model.

User.ReadWrite.All is also problematic here, unless there is a good reason for it.

## Screenshots

![image (12)](https://user-images.githubusercontent.com/1481108/92945979-0c43ee80-f424-11ea-81cf-c82ef96ff294.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Update the docs to illustrate why these permissions are needed, or implement a new set of permissions to better follow a least privilege model.

**Comment by glicht** [comment]
@ryanspletzer thanks for reporting this. We will review and update.
