### ISSUE TITLE
Issue with "Set" in @site/docs/reference/scripts/set.md

### ISSUE THREAD

**Issue by matan-xmcyber** [demisto/content-docs#311]
## Describe the problem

* Page: [Set](https://xsoar.pan.dev/docs/reference/scripts/set)
* Source: https://github.com/demisto/content/blob/master//Packs/CommonScripts/Scripts/script-Set_README.md

The documentation mentions "The value to set to the key. Can be an array. Usually, a DQ expression.", but what is a DQ expression?

**Comment by glicht** [comment]
@matan-xmcyber thanks for reporting this. We will update the doc.
