### ISSUE TITLE
Issue with "Palo Alto Networks PAN-OS" in @site/docs/reference/integrations/panorama.md

### ISSUE THREAD

**Issue by apekarovsky** [demisto/content-docs#312]
## Describe the problem

* Page: [Palo Alto Networks PAN-OS](https://xsoar.pan.dev/docs/reference/integrations/panorama)
* Source: https://github.com/demisto/content/blob/master//Packs/PAN-OS/Integrations/Panorama/README.md

Bullets 55 - 77 are missing.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Add the relevant bullets.

**Comment by glicht** [comment]
Thanks for reporting this. We will check this out and update the docs accordingly.

**Comment by glicht** [comment]
fixed at: https://github.com/demisto/content/pull/9490
