### ISSUE TITLE
Issue with "Contributing from Cortex XSOAR UI" in @site/docs/contributing/marketplace.md

### ISSUE THREAD

**Issue by mycacao** [demisto/content-docs#340]
## Describe the problem

* Page: [Contributing from Cortex XSOAR UI](https://xsoar.pan.dev/docs/contributing/marketplace)
* Source: https://github.com/demisto/content-docs/tree/master/docs/contributing/marketplace.md

## Suggested fix
There is a typo => explainingi. it needs to fix with right word.

**Comment by Itay4** [comment]
@mycacao thanks for reporting this, we will handle it
