### ISSUE TITLE
Issue with "AWS - EC2" in @site/docs/reference/integrations/aws---ec2.md

### ISSUE THREAD

**Issue by KyleZevenbergen** [demisto/content-docs#343]
## Describe the problem
We should at least document the commands, what they do, and describe arguments so people don't have to dig into the code and try to translate the XSOAR command they are calling to the boto call it initiates.
* Page: [AWS - EC2](https://xsoar.pan.dev/docs/reference/integrations/aws---ec2)
* Source: https://github.com/demisto/content/blob/master//Packs/AWS-EC2/Integrations/AWS-EC2/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
@KyleZevenbergen Thanks for reporting. We are working on improving this.

**Comment by glicht** [comment]
Fixed at: https://github.com/demisto/content/pull/9500
