### ISSUE TITLE
Issue with "Context Standards" in @site/docs/integrations/context-standards.md

### ISSUE THREAD

**Issue by matan-xmcyber** [demisto/content-docs#346]
## Describe the problem

* Page: [Context Standards](https://xsoar.pan.dev/docs/integrations/context-standards)
* Source: https://github.com/demisto/content-docs/tree/master/docs/integrations/context-standards.md

Missing YAML format for Endpoint and Process, Directory, Event, Rule and a few others

![image](https://user-images.githubusercontent.com/70726085/96143037-b8b83b00-0ed0-11eb-8d04-265a21b53abe.png)

**Comment by fvigo** [comment]
Thanks for notifying the issue.

Resolved in: #299
