### ISSUE TITLE
Issue with "Classification and Mapping" in @site/docs/incidents/incident-classification-mapping.md

### ISSUE THREAD

**Issue by urjitgokhale** [demisto/content-docs#375]
In the Classification section the page, the link in the last sentence - "For information about defining the incident type within the integration settings, **see XSOAR Dev Hub**." - does not take the reader to a specific example. It takes the user to the main dev hub page. And searching for the specific example from there is non-trivial.

The request is to fix the link so the user is taken to the exact information about '_defining the incident type within the integration settings_'.

* Page: [Classification and Mapping](https://xsoar.pan.dev/docs/incidents/incident-classification-mapping#classification)
* Source: https://github.com/demisto/content-docs/tree/master/docs/incidents/incident-classification-mapping.md

**Comment by glicht** [comment]
@urjitgokhale thanks for reporting this. We will add a better link.
