### ISSUE TITLE
Issue with "EmailAskUser" in @site/docs/reference/scripts/email-ask-user.md

### ISSUE THREAD

**Issue by djmasters** [demisto/content-docs#385]
## Describe the problem

* Page: [EmailAskUser](https://xsoar.pan.dev/docs/reference/scripts/email-ask-user)
* Source: https://github.com/demisto/content/blob/master//Packs/CommonScripts/Scripts/script-EmailAskUser_README.md

The EmailAskUser (and corresponding EmailAskUserResponse) flow is not clearly defined for our customers; in particular the way that the closed task is used.

## Screenshots
NA

## Environment
NA

## Suggested fix

I suggest providing an example flow such as:

----------------------------------------------------

An example arrangement for EmailAskUser task is as below:

![image](https://user-images.githubusercontent.com/54623333/99517136-efc5b480-2986-11eb-879c-a0a88923c4b9.png)

There needs to be a manual conditional task *after* the EmailAskUser Task - It's this task that is referenced as "task" in the EmailAskUser parameters.

It is good practice to tag the wait task as shown:

![image](https://user-images.githubusercontent.com/54623333/99517219-0409b180-2987-11eb-9aa4-7e96b2a12238.png)

The tag you choose (in this case "Await") can be used in lieu of the task id in the task field of the EmailAskUser Task:

![image](https://user-images.githubusercontent.com/54623333/99517256-0f5cdd00-2987-11eb-8a1f-1dc41d166b42.png)

-----------------------------

**Comment by glicht** [comment]
@djmasters thanks for reporting this. Will add this to the doc.
