### ISSUE TITLE
Issue with "Proofpoint TAP v2" in @site/docs/reference/integrations/proofpoint-tap-v2.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#392]
## Describe the problem

* Page: [Proofpoint TAP v2](https://xsoar.pan.dev/docs/reference/integrations/proofpoint-tap-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/readme.md

There is an inaccuray in the Description text : 
> Use the Proofpoint Targeted Attack Protection (TAP) integration to protect against and provide additional visibility into phishing and other malicious email attacks. This integration was integrated and tested with version xx of Proofpoint TAP v2
> version xx

## Suggested fix

Specify the version that was tested instead of xx

**Comment by glicht** [comment]
@Itay4 are you updating this?
