### ISSUE TITLE
Issue with "Check Point Firewall v2" in @site/docs/reference/integrations/check-point-firewall-v2.md

### ISSUE THREAD

**Issue by FFrozTT** [demisto/content-docs#394]
In it's current state it may work well for connecting to a standalone management server however connecting to an MDS ("Multi Domain Server") will require the parameter Domain to be included in the JSON body of the checkpoint_login_and_get_sid_command function.  So instead of this:

```
{
    "user":"<Username>",
    "password":"<Password>"
}
```
 it will need this:
```
{
    "user":"<Username>",
    "password":"<Password>",
    "domain" : "<CMA Domain>"
}
```

Of course I'm trying to connect to my MDS so I really need this domain parameter mapped.  It probably makes the most sense to create a new function for this, something like checkpoint_mds_login_and_get_sid_command which has the domain parameter as a required string.

[https://sc1.checkpoint.com/documents/latest/APIs/#web/login~v1.7%20](https://sc1.checkpoint.com/documents/latest/APIs/#web/login~v1.7%20)

Thanks!

* Page: [Check Point Firewall v2](https://xsoar.pan.dev/docs/reference/integrations/check-point-firewall-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by FFrozTT** [comment]
So this would be my attempt at the function, not tested:
```
def checkpoint_mds_login_and_get_sid_command(base_url: str, username: str, password: str,
                                         verify_certificate: bool,
                                         domain: string,
                                         session_timeout: int) -> CommandResults:
    """login to checkpoint admin account using username and password."""
    response = requests.post(base_url + 'login', verify=verify_certificate,
                             headers={'Content-Type': 'application/json'},
                             json={'user': username, 'password': password,
                                   'domain': domain,
                                   'session-timeout': session_timeout}).json()
    printable_result = {'session-id': response.get('sid')}
    readable_output = tableToMarkdown('CheckPoint session data:', printable_result)

    command_results = CommandResults(
        outputs_prefix='CheckPoint.Login',
        outputs_key_field='uid',
        readable_output=readable_output,
        outputs=printable_result,
        raw_response=response
    )
    return command_results
```

**Comment by glicht** [comment]
@FFrozTT thanks for reporting this. I see you opened a PR. Your contribution is appreciated. The team will review the PR and get back to you soon.

**Comment by glicht** [comment]
Relevant pr: https://github.com/demisto/content/pull/10356
