### ISSUE TITLE
Issue with submitting the playbook as contribution in XSOAR

### ISSUE THREAD

**Issue by shubgwal-gif** [demisto/content-docs#403]
when i am trying to submit a playbook as contribution in xsoar than i am getting error as " Failed License verification ". Can you please help me to resolve this error .

**Comment by Itay4** [comment]
Hi @shubgwal-gif 
This repository is for the Cortex XSOAR docs site, and hence only issues related to docs are tracked here.
Please open a support ticket for the issue you are experiencing so it can be handled properly.
Thanks
