### ISSUE TITLE
Install Shared Agent Tech Documenation

### ISSUE THREAD

**Issue by synth-humbert** [demisto/content-docs#405]
## Describe the problem
Steps 2.4 and 3.2 both need the command updated.

## Screenshots
<img width="310" alt="2020-12-08 15_51_58-#46 Create Agent - War Room" src="https://user-images.githubusercontent.com/72804710/101788162-6e64cc00-3ac5-11eb-91f0-715d0674e7e2.png">
<img width="379" alt="2020-12-08 15_51_47-#46 Create Agent - War Room" src="https://user-images.githubusercontent.com/72804710/101788166-6efd6280-3ac5-11eb-9edb-40e63e1636f4.png">

## Environment
N/A

## Suggested fix
Alter Steps 2.4 and 3.2 to use execute command referenced in screenshots with mandatory fields cmd, system, and script filled in.

## Additional Information
Maybe a bug on mandatory fields, currently requires both cmd and script be supplied, I'd expect it to be either or both. Another ticket may need to be created for command bug. Please advise.

**Comment by synth-humbert** [comment]
Forgot to append reference url
https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-0/cortex-xsoar-admin/agents/shared-agents/install-a-shared-agent.html#id2bad2125-3dc3-4e9d-b64e-1e78fecfb3ae

**Comment by Itay4** [comment]
Hi @synth-humbert, thanks for reaching out
This repository is related to https://xsoar.pan.dev/ and not to https://docs.paloaltonetworks.com 
Please open a support ticket for this request
