### ISSUE TITLE
Issue with "Gmail Single User (Beta)" in @site/docs/reference/integrations/gmail-single-user.md

### ISSUE THREAD

**Issue by netzwerg-au** [demisto/content-docs#408]
Gmail Single User (Beta) documentation missing steps required for building own Google app

* Page: [Gmail Single User (Beta)](https://xsoar.pan.dev/docs/reference/integrations/gmail-single-user)
* Source: https://github.com/demisto/content/blob/master//Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md

This page is missing required information to help a user build their own Google app, rather than use the Demisto app (which Google won't allow to auth to my personal account.  When creating the iOS OAuth Client ID, the user is required to enter the Bundle ID, but no guidance is given as to what this Bundle ID should be, or where to find it.

## Screenshots
<img width="564" alt="Screen Shot 2020-12-16 at 12 30 12 pm" src="https://user-images.githubusercontent.com/30072974/102293196-ade65900-3f9a-11eb-9cea-891f6da7fe7c.png">

## Environment
N/A

## Suggested fix
More detailed documentation required.

**Comment by glicht** [comment]
Thanks for reporting this. We will take a look.
