### ISSUE TITLE
Issue with "SetGridField" in @site/docs/reference/scripts/set-grid-field.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#419]
The keys in the command examples are wrong. should be :
!SetGridField columns="columnheade1,columnheade2,columnheade3" context_path=EWS.Items.headers grid_id=mygrid keys="name,value"

**Comment by sylvainmeras** [comment]
Also column name in the command do not fit with the column name in the grid screenshot

**Comment by fvigo** [comment]
@GalRabin please take a look when you have a chance
