### ISSUE TITLE
Issue with "Create an Integration" in @site/docs/tutorials/tut-integration-ui.md : Missing image for Short Text param API URL

### ISSUE THREAD

**Issue by vibhuabharadwaj** [demisto/content-docs#454]
## Describe the problem

* Page: [Create an Integration](https://xsoar.pan.dev/docs/tutorials/tut-integration-ui)
* Source: https://github.com/demisto/content-docs/tree/master/docs/tutorials/tut-integration-ui.md

The API Encrypted param type is repeated twice in the image. First image should be API URL as short text according to description.

## Screenshots
![Screen Shot 2021-01-18 at 1 42 09 PM](https://user-images.githubusercontent.com/53234515/104965164-f9719580-5992-11eb-9bdf-e342bf6b5893.png)

## Environment
 - OS: Mac
 - Browser: Chrome
 - Browser Version: 87.0.4280.141

**Comment by glicht** [comment]
@vibhuabharadwaj thanks for reporting this. Will be fixed soon.
