### ISSUE TITLE
Issue with "Shift handover" in @site/docs/reference/playbooks/shift-handover.md

### ISSUE THREAD

**Issue by jasonhatgithub** [demisto/content-docs#475]
## Describe the problem

* Page: [Shift handover](https://xsoar.pan.dev/docs/reference/playbooks/shift-handover)
* Source: https://github.com/demisto/content/blob/master//Packs/ShiftManagement/Playbooks/Shift_handover_README.md

The image for the flow is not readable due to heavily compressed image

## Environment
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: latest for 2021-02-05

## Suggested fix
re-upload original image

**Comment by glicht** [comment]
@evisochek can you take a look

**Comment by evisochek** [comment]
Resolved by:
https://github.com/demisto/content/pull/11436
