### ISSUE TITLE
Issues with links to subdirectories in docs

### ISSUE THREAD

**Issue by csestito** [demisto/content-docs#51]
## Describe the problem
Due to new docs structure, some links seem to be broken, I found one as example

## Screenshots

![Tutorials](https://i.imgur.com/VVU7mkT.png)
## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix
Fix all links, verify they lead somewhere

**Comment by fvigo** [comment]
Fixed in #62  , please verify. tnx
