### ISSUE TITLE
Issue with "YaraScan" in @site/docs/reference/scripts/yara-scan.md

### ISSUE THREAD

**Issue by Indoye** [demisto/content-docs#513]
## Describe the problem

* Page: [YaraScan](https://xsoar.pan.dev/docs/reference/scripts/yara-scan)
* Source: https://github.com/demisto/content/blob/master//Packs/Yara/Scripts/YaraScan/YaraScan_README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
Hi @Indoye , thanks for opening your first issue. It looks like you didn't provide details regarding the problem.

Please describe what you've encountered and if you have a suggested fix please include that too.

**Comment by glicht** [comment]
Closing for now. Feel free to re-open with more details.
