### ISSUE TITLE
Issue with "Debugging" in @site/docs/integrations/debugging.md

### ISSUE THREAD

**Issue by p0pe1e** [demisto/content-docs#519]
## Describe the problem

* Page: [Debugging](https://xsoar.pan.dev/docs/integrations/debugging)
* Source: https://github.com/demisto/content-docs/tree/master/docs/integrations/debugging.md

The first section of this doc, does not make too much sense....

## Screenshots

![image](https://user-images.githubusercontent.com/1097421/109835877-7893f380-7bf8-11eb-9c25-9dacda8cac9b.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by Itay4** [comment]
@fvigo can you please have a look?
