### ISSUE TITLE
Issue with "Securonix" in @site/docs/reference/integrations/securonix.md

### ISSUE THREAD

**Issue by hfondse** [demisto/content-docs#550]
Currently we are ingesting alerts from Securonix into XSOAR but we have no method to close the incidents on Securonix from xsoar. There is a command to issue an action onto an incident that we can possibly use but we don't know what the arguments are to close the incident. We have tried multiple options by guessing but with no success.

securonix-perform-action-on-incident action=????

Can we please have the arguments to close a specific incident so that we can build it into our playbooks?

## Describe the problem

* Page: [Securonix](https://xsoar.pan.dev/docs/reference/integrations/securonix)
* Source: https://github.com/demisto/content/blob/master//Packs/Securonix/Integrations/Securonix/README.md

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by Itay4** [comment]
@bakatzir can you please assist here?

**Comment by bakatzir** [comment]
@hfondse The actions available on an incident are per the workflow the incident is associated to.
I would run `securonix-get-incident-workflow` on the incident first.
then `securonix-get-incident-available-actions`.
IIRC, in the default workflow, an unassigned incident can not be closed directly, and it has to be assigned first.
That said, every customer has it is own unique workflows.
