### ISSUE TITLE
Issue with missing "Windows Remote Management (Beta)" in @site/docs/reference/integrations/

### ISSUE THREAD

**Issue by gomesian** [demisto/content-docs#557]
## Describe the problem

In market place, but missing in https://xsoar.pan.dev/docs/reference/integrations/

## Screenshots
n/a

## Environment
n/a

## Suggested fix
add page - describing how to use 'scriptname' is how we ran into this issue of missing documentation.

**Comment by glicht** [comment]
Fixed at: https://github.com/demisto/content/pull/12131
