### ISSUE TITLE
Issue with "ReadPDFFileV2" in @site/docs/reference/scripts/read-pdf-file-v2.md

### ISSUE THREAD

**Issue by DanteDevil89** [demisto/content-docs#653]
## Describe the problem

There is no information on how to process files that do not have "entryID"

* Page: [ReadPDFFileV2](https://xsoar.pan.dev/docs/reference/scripts/read-pdf-file-v2)
* Source: https://github.com/demisto/content/blob/master//Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_README.md

## Environment
 - OS: All
 - Browser: All
 - Browser Version: All

## Suggested fix

Add file processing with file name

**Comment by Itay4** [comment]
hi @DanteDevil89 
`entryID` is a required argument for the script and hence you can not run it without it
i'm gonna close the issue but feel free to ask for clarifications if needed

**Comment by DanteDevil89** [comment]
Not all files have the entryid, how can I assign it?

**Comment by Itay4** [comment]
@DanteDevil89 please advice with the customer support on that
