### ISSUE TITLE
Issue with "Create an Integration" in @site/docs/tutorials/tut-integration-ui.md

### ISSUE THREAD

**Issue by XSOARONE** [demisto/content-docs#667]
## Describe the problem

* Page: [Create an Integration](https://xsoar.pan.dev/docs/tutorials/tut-integration-ui)
* Source: https://github.com/demisto/content-docs/tree/master/docs/tutorials/tut-integration-ui.md

firstly, Code is not well ordered, after I finished the tutorial and comparing my code to the complete code, where you mentioned your could should look like this, I had to reorganize my code many times.

second thing the script helper, lacks the error and markdown that you said you can find them there and use it.
and lastly, there was a complete if statment inside the command that you never mentioned in steps to build the integration?!!

![image](https://user-images.githubusercontent.com/85355667/120819053-3b772e80-c564-11eb-91af-d09cbd20032c.png)

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by glicht** [comment]
@XSOARONE nice github user! 

Thanks for the feedback. We have an internal task to refresh the tutorial. Your feedback has been noted. I am closing this issue as we have plans to do a total refresh.
