### ISSUE TITLE
Issue with "Content Packs Structure" in @site/docs/integrations/packs-format.md

### ISSUE THREAD

**Issue by mhouston007** [demisto/content-docs#72]
## Describe the problem
Broken link to demisto-sdk readme's and a couple of typos

## Screenshots
![image](https://user-images.githubusercontent.com/58996090/78054441-124f8280-7350-11ea-84ad-b1a9b3b3ce43.png)

## Fix
Typos: `pre-commit hook to check that possible`
Fix link to point to correct location: https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/secrets

**Comment by glicht** [comment]
Thanks for reporting this. Good catch.
