### ISSUE TITLE
Issue with https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000PPEuCAO

### ISSUE THREAD

**Issue by cpayne-panw** [demisto/content-docs#729]
## Describe the problem

* Page: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000PPEuCAO
* Source: UNK

In step 1 of the procedure on https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000PPEuCAO  The port is 8443 and I believe it should be 443.

## Screenshots

![image](https://user-images.githubusercontent.com/85252788/126671519-7d948f8f-eb48-4b3c-bdf3-2dc4c59ecda0.png)

## Environment
 - OS: [e.g. Windows]: n/a
 - Browser: [e.g. chrome, safari, firefox..] n/a
 - Browser Version: n/a

## Suggested fix
see description.  But I'm not sure if this is a legacy port or not from older versions....

**Comment by reutshal** [comment]
Thanks for catching this! The issue shouldn't be here though, I opened a new one in etc:
https://github.com/demisto/etc/issues/39477

Closing.
