### ISSUE TITLE
Issue with "FortiAuthenticator" in @site/docs/reference/integrations/forti-authenticator.md

### ISSUE THREAD

**Issue by fahad0707** [demisto/content-docs#743]
Looks you are referencing "localusers" and the integration is failing for LDAP users.
I replaced /localusers with /ldapusers and integration worked. 
I am a bit skeptical about the change I made as I have no or very little programming skills. 
However I think you might have understood and may be publish the new content package to marketplace. 

---------------------------------------------------
        res = requests.patch(BASE_URL + 'localusers/' + userID + '/', data=jsonData, auth=(USER_NAME, PASSWORD), verify=USE_SSL)

        if res.status_code == 202:
            user_context.append({
                'username': userItems["objects"][0]["username"],
                'email': userItems["objects"][0]["email"],
                'active': active,
                'id': userItems["objects"][0]["id"]
            })

**Comment by jasonlo82** [comment]
> Looks you are referencing "localusers" and the integration is failing for LDAP users.
> I replaced /localusers with /ldapusers and integration worked.
> I am a bit skeptical about the change I made as I have no or very little programming skills.
> However I think you might have understood and may be publish the new content package to marketplace.
> 
> ```
>     res = requests.patch(BASE_URL + 'localusers/' + userID + '/', data=jsonData, auth=(USER_NAME, PASSWORD), verify=USE_SSL)
> 
>     if res.status_code == 202:
>         user_context.append({
>             'username': userItems["objects"][0]["username"],
>             'email': userItems["objects"][0]["email"],
>             'active': active,
>             'id': userItems["objects"][0]["id"]
>         })
> ```

@fahad0707 Thanks for reporting this. The "localusers" should be replaced by the variable userType. I will update it ASAP.
