### ISSUE TITLE
Issue with "Slack v3 (beta)" in @site/docs/reference/integrations/slack-v3.md

### ISSUE THREAD

**Issue by klamontagne-om** [demisto/content-docs#745]
## Describe the problem

* Page: [Slack v3 (beta)](https://xsoar.pan.dev/docs/reference/integrations/slack-v3)
* Source: https://github.com/demisto/content/blob/master//Packs/Slack/Integrations/SlackV3/README.md

The linked App Manifest (https://raw.githubusercontent.com/demisto/content/master/Packs/Slack/doc_files/SlackV3_app_manifest.yml) does not have enough permissions to use !mirror-investigation

## Suggested fix

Update the manifest file to contain the correct permissions, or call out that the default provided permissions won't support certain functions

**Comment by amshamah419** [comment]
This was fixed over the weekend here - https://github.com/demisto/content/pull/14037
