### ISSUE TITLE
Buttons not displayed in @site/docs/get-started.md

### ISSUE THREAD

**Issue by fvigo** [demisto/content-docs#8]
Buttons (i.e. Sign Up Now and Download the partnership agreement) are not displayed in the rendered file. They are displayed in the v1 website  (https://demisto.developers.paloaltonetworks.com/docs/en/get-started)

**Comment by sserrata** [comment]
Fix has been merged but I noticed the Partner Agreement PDF link is broken. I'll try to get a copy from the v1 repository.

**Comment by fvigo** [comment]
Resolved with #10
