### ISSUE TITLE
Issue with "MITRE ATT&CK - Courses of Action" in @site/docs/reference/articles/courses-of-action.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#816]
## Describe the problem

Wrong copy / paste in the Unit 42 Feed chapter

* Page: [MITRE ATT&CK - Courses of Action](https://xsoar.pan.dev/docs/reference/articles/courses-of-action)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/articles/CoA-premium-pack-readme.md

## Suggested fix

In Unit 42 Feed chapter, sentence shall be "The Courses of Action pack and playbooks work with both versions of the Unit 42 Feed pack." instead of "The Courses of Action pack and playbooks work with both versions of the MITRE ATT&CK pack."

**Comment by yuvalbenshalom** [comment]
this is not updated any more.

the page is now in https://xsoar.pan.dev/docs/reference/packs/courses-of-action
and in the repo it was moved to: https://github.com/demisto/content-repo/extra-docs/packs/CoA-premium-pack-readme.md.
