### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mhouston007** [demisto/content-docs#83]
## Describe the problem
Did a quick web crawl to get all the links in https://demisto.pan.dev/docs/welcome, and checked them to see if any were broken, will try to update this output to find the pages these links are located at:

- https://demisto.pan.dev/docs/partners/why-demisto  404
- https://demisto.pan.dev/Tests/scripts/hook_validations/integration.py  404
- https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/init/init_command.md  404
- https://demisto.pan.dev/Integrations/Kafka_V2/Kafka_V2.yml  404
- https://xsoar.pan.dev/docs/reference  404
- https://demisto.pan.dev/docs/howtos/integrations/packs-format  404
- https://demisto.pan.dev/docs/howtos/integrations/testing  404
- https://github.com/demisto/demisto-sdk/blob/master/docs/validate_command.md  404
- https://github.com/demisto/demisto-sdk/blob/master/docs/lint_command.md  404
- https://demisto.pan.dev/docs/.hooks/bootstrap  404
- https://demisto.pan.dev/docs/dev-requirements-py2.txt  404
- https://demisto.pan.dev/docs/dev-requirements-py3.txt  404
- https://demisto.pan.dev/docs/Tests/scripts/hook_validations/integration.py  404
- https://github.com/demisto/content/blob/master/Integrations/Slack/README.md  404

## Screenshots
![chrome_YnZlFdkX1P](https://user-images.githubusercontent.com/58996090/78301434-0d80ff00-7507-11ea-91c3-340999066117.png)
![chrome_GcCguYrSLA](https://user-images.githubusercontent.com/58996090/78301448-0f4ac280-7507-11ea-893c-3e0aa80618e4.png)

## Suggested fix
Update or remove links

**Comment by fvigo** [comment]
Thanks for reporting this @mhouston007 !
