### ISSUE TITLE
Issue with "Generic Webhook" in @site/docs/reference/integrations/generic-webhook.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#837]
## Describe the problem

* Page: [Generic Webhook](https://xsoar.pan.dev/docs/reference/integrations/generic-webhook)
* Source: https://github.com/demisto/content/blob/master//Packs/GenericWebhook/Integrations/GenericWebhook/README.md

This command:
`curl -POST https://my.demisto.live/instance/execute/webhook -H "Authorization: token" -d '{"name":"incident created via generic webhook","raw_json":{"some_field":"some_value"}}'
`

Requires `-H "Content-Type: application/json"`

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by reutshal** [comment]
@sylvainmeras Thanks for your feedback! We've added the fix to the README.
