### ISSUE TITLE
Issue with "Reference Docs" in @site/docs/reference/index.md

### ISSUE THREAD

**Issue by t0nyurban** [demisto/content-docs#839]
## Describe the problem

* Page: [Reference Docs](https://xsoar.pan.dev/docs/reference/index)
* Source: 
The link for jira-v2 integration (https://xsoar.pan.dev/docs/reference/index/integrations/jira-v2) is broken

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by reutshal** [comment]
@t0nyurban Thanks for opening this issue!
Where did you get this link? From the integrations section, the link to the integration is this one: https://xsoar.pan.dev/docs/reference/integrations/jira-v2 
And it is not broken

**Comment by t0nyurban** [comment]
Yes, it appears to be working, I think it may have something to do with my
browser authentication.  I typically have to do a reload of the page to get
it to work if I get the 'page not found' error.  I've seen it with other
links on the site so I know how to get around it.

Thanks for the follow up.

Tony

**Comment by reutshal** [comment]
Closing as this was fixed by https://github.com/demisto/content-docs/pull/850
