### ISSUE TITLE
Broken link 'autogenerated' in Playbook section

### ISSUE THREAD

**Issue by kgal-pan** [demisto/content-docs#843]
## Describe the problem

* Page: [Contribution Checklist](https://xsoar.pan.dev/docs/contributing/checklist)
* Source: https://github.com/demisto/content-docs/tree/master/docs/contributing/checklist.md

In [Playbook](https://xsoar.pan.dev/docs/contributing/checklist/#playbooks) section, the link under the word `autogenerated` (https://xsoar.pan.dev/docs/contributing/documentation/readme_file#creating-documentation) is broken:

> for README file (i.e. Packs/YourPackName/Playbooks/playbook-YourPlaybookName_README.md): documentation file for the Playbook, mostly autogenerated

```bash
# print only HTTP response status code
curl -s -o /dev/null -w "%{http_code}" https://xsoar.pan.dev/docs/contributing/documentation/readme_file
404
```

## Screenshots
![image](https://user-images.githubusercontent.com/85439776/139942371-8c0dbed7-6676-4c76-8a57-ff126e9f9491.png)

![image](https://user-images.githubusercontent.com/85439776/139942176-8b55939a-ecf5-4a01-9db2-7f1d5ead0975.png)

## Environment
 - OS: Mac Big Sur 11.6 (20G165)
 - Browser: Chrome
 - Browser Version: 95.0.4638.54 (Official Build) (x86_64)

**Comment by reutshal** [comment]
Closing as this was fixed by https://github.com/demisto/content-docs/pull/850
