### ISSUE TITLE
Issue with "Visual Studio Code Extension" in @site/docs/concepts/vscode-extension.md

### ISSUE THREAD

**Issue by gomesian** [demisto/content-docs#845]
## Describe the problem

* Page: [Visual Studio Code Extension](https://xsoar.pan.dev/docs/concepts/vscode-extension)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/vscode-extension.md

The link in page (under Debugging section) " Read the Debugging using your IDE section" is broken.. Page not found.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by reutshal** [comment]
Closing as this was fixed by https://github.com/demisto/content-docs/pull/850
