### ISSUE TITLE
Issue with "Contribution Design" in @site/docs/tutorials/tut-design.md

### ISSUE THREAD

**Issue by Pinger77** [demisto/content-docs#846]
## Describe the problem

* Page: [Contribution Design](https://xsoar.pan.dev/docs/tutorials/tut-design)
* Source: https://github.com/demisto/content-docs/tree/master/docs/tutorials/tut-design.md

The links in the following section no longer work.
https://xsoar.pan.dev/docs/tutorials/tut-design/#classifiers-mappers-types-fields-and-layouts
 

## Screenshots

![Uploading image.png…]()

**Comment by reutshal** [comment]
Closing as this was fixed by https://github.com/demisto/content-docs/pull/850
