### ISSUE TITLE
Issue with "Palo Alto Networks Threat Vault" in @site/docs/reference/integrations/palo-alto-networks-threat-vault.md

### ISSUE THREAD

**Issue by gomesian** [demisto/content-docs#856]
## Describe the problem

* Page: [Palo Alto Networks Threat Vault](https://xsoar.pan.dev/docs/reference/integrations/palo-alto-networks-threat-vault)
* Source: https://github.com/demisto/content/blob/master//Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md

We are presenting two clickable malicious links in our page. Please consider for removal ASAP

//www.google.com.shufaren.com.cn//
//www.google.com-document-view.alibabatradegroup.com//

## Screenshots

![image](https://user-images.githubusercontent.com/73147163/141369394-913c0e55-0c98-4a27-a349-4cbad10c82de.png)

**Comment by glicht** [comment]
@gomesian thanks for reporting this. Will be fixed soon.
