### ISSUE TITLE
Issue with "Visual Studio Code Extension" in @site/docs/concepts/vscode-extension.md

### ISSUE THREAD

**Issue by rurhrlaub** [demisto/content-docs#857]
## Describe the problem

* Page: [Visual Studio Code Extension](https://xsoar.pan.dev/docs/concepts/vscode-extension)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/vscode-extension.md

Customers find it difficult to follow and asked for CS help and we found it a bit difficult to follow as well.  I documented a sequential start to finish process that may be of use. See attached as an example (in my case for Mac OS):

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

[CCS-HowToSetUpVisualStudioCodewithXSOAR-121121-0707-130.pdf](https://github.com/demisto/content-docs/files/7528517/CCS-HowToSetUpVisualStudioCodewithXSOAR-121121-0707-130.pdf)

**Comment by jochman** [comment]
Thank you @rurhrlaub for your suggestion, we really appreciate it!
We've considered it and found the setup instructions a little too specific and excessive. However, we decided to add a clarification to how to install the demisto-sdk and the requirement to set up environment variables.
