### ISSUE TITLE
Issue with "Development Partners" in @site/docs/partners/development-partners.md

### ISSUE THREAD

**Issue by sylvainmeras** [demisto/content-docs#86]
## Describe the problem
Link to partner-owned integration is wrong in https://xsoar.pan.dev/docs/partners/development-partners#how-it-works #5 - 

## Suggested fix
It should be: https://xsoar.pan.dev/docs/partners/partner-owned-integration

**Comment by glicht** [comment]
It seems ok now. Maybe you were looking at an old version.
