### ISSUE TITLE
Issue with "Cortex XSOAR Content Release Notes for version 21.11.1 (8953251)" in @site/docs/reference/releases/21.11.1.md

### ISSUE THREAD

**Issue by zhiwangprisma** [demisto/content-docs#886]
## Describe the problem

* Page: [Cortex XSOAR Content Release Notes for version 21.11.1 (8953251)](https://xsoar.pan.dev/docs/reference/releases/21.11.1)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/releases/21.11.1.md
* After I close the incidents, the additional info on incident detail page doesn't get updated to close properly, even after page refresh.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by Itay4** [comment]
@zhiwangprisma hi

this issue tracker is for documentation issues related to xsoar.pan.dev

please contact customer support so they can assist you're having with the platform
