### ISSUE TITLE
Issue with "Contributing" in @site/docs/contributing/contributing.md

### ISSUE THREAD

**Issue by ali-sawyer** [demisto/content-docs#889]
## Describe the problem
Request for improvement (missing information):  In the line "For more information about the different support levels, check the official documentation" on this page where "official documentation" is hyperlinked, the link is broken and takes the user to a generic XSOAR docs page. Searching around, I could not find a more detailed page describing support levels in the XSOAR documentation. Could such a page be added/found and then linked here?

* Page: [Contributing](https://xsoar.pan.dev/docs/contributing/contributing)
* Source: https://github.com/demisto/content-docs/tree/master/docs/contributing/contributing.md

## Screenshots
<img width="849" alt="Screen Shot 2021-12-16 at 4 59 21 PM" src="https://user-images.githubusercontent.com/91506078/146466449-a1fdf5b3-e887-4d42-b030-e5b2a5fe9218.png">

## Environment
 - OS: Mac
 - Browser: Chrome
 - Browser Version: 96.0.4664.55

## Suggested fix

Add detailed page describing support levels (esp. exactly what the different content standards/quality requirements are for each support level) and link it here.

**Comment by Itay4** [comment]
@ali-sawyer thanks for reporting this, we'll fix this soon

in the mean time, here is the link https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/marketplace/content-packs-support-types.html
