### ISSUE TITLE
Issue with "Contributing via Cortex XSOAR" in @site/docs/contributing/marketplace.md

### ISSUE THREAD

**Issue by ali-sawyer** [demisto/content-docs#894]
## Describe the problem

* Page: [Contributing via Cortex XSOAR](https://xsoar.pan.dev/docs/contributing/marketplace)
* Source: https://github.com/demisto/content-docs/tree/master/docs/contributing/marketplace.md

I was asked a question I do not know the answer to:

When Contributing a modification to an existing Content Pack, which Update Type should be selected in which cases (e.g., if adding a new command)? Please list out the Update Types and add a description for each. The options are:
- Revision
- Minor
- Major
- Documentation

## Environment
 - OS: Mac
 - Browser: Chrome
 - Browser Version: 96.0.4664.110

## Suggested fix
List out the different Update Type options and add a description + example for each.

**Comment by Itay4** [comment]
@ali-sawyer hi

thanks for reporting this

we are tracking this internally and will make sure to update once we have the docs in place
