### ISSUE TITLE
Issue with "Demisto SDK" in @site/docs/concepts/demisto-sdk.md

### ISSUE THREAD

**Issue by dannyjea** [demisto/content-docs#921]
## Describe the problem

* Page: [Demisto SDK](https://xsoar.pan.dev/docs/concepts/demisto-sdk)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/demisto-sdk.md

I have just set up a new Windows machine with updates, installed Python, installed MS Visual Studio Code, the Python extension and I go to do the final step of install demisto-sdk, at which point the documentation tells me I should have set all this up on Linux. I appreciate I could use WSL but this adds additional complexity that I am trying to avoid.

Since demisto-sdk is a key element and is recommended to run on macOS or Linux, can you add a note higher in the documentation set to prevent wasted time.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

## Suggested fix

Since demisto-sdk is a key element and is recommended to run on macOS or Linux, can you add a note higher in the documentation set to prevent wasted time.

**Comment by Itay4** [comment]
@dannyjea the WSL prerequisite is in the first paragraph in https://xsoar.pan.dev/docs/concepts/demisto-sdk#installation-and-setup which is at the top of the document
also, it is in the [contribution requirements](https://xsoar.pan.dev/docs/contributing/contrib-requirements#development-os)

where else do you expect to see it?

**Comment by dannyjea** [comment]
Hi

Thanks for the response, on the web page https://xsoar.pan.dev/docs/concepts/xsoar-ide under developing the demisto-sdk page is listed last after Cortex XSOAR IDE, PyCharm IDE, VSCode extension and dev set up. By the time I reached the demisto sdk document page I had already set up a Windows environment, if the info about SDK could be added to the cortex xsoar ide page (or some other solution) I would have started my setup using Linux. Hope that makes sense.

Regards
Danny

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Itay4** [comment]
the Cortex XSOAR IDE and the PyCharm IDE Plugin do not require the Demisto SDK, but do refer to the VSCode Extension, which one of its prerequisites is the Demisto SDK and refers to the page i mentioned in my previous comment - did you miss that ?

**Comment by dannyjea** [comment]
Probably, I will take another look. Thanks for your support.

Regards
Danny

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Itay4** [comment]
sure no problem 👍 

if you don't mind, i'm gonna close this one for now

feel free to reopen it or open a new issue if you have a suggestion on how we can improve our documentation
