### ISSUE TITLE
Issue with "Cortex XSOAR Content Release Notes for version 22.1.0 (10320303)" in @site/docs/reference/releases/22.1.0.md

### ISSUE THREAD

**Issue by PaulBartruff** [demisto/content-docs#971]
## Describe the problem

* Page: [Cortex XSOAR Content Release Notes for version 22.1.0 (10320303)](https://xsoar.pan.dev/docs/reference/releases/22.1.0)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/releases/22.1.0.md

6.5 appears to be a new minimum version for many content packs.  I found 21 references to 6.5 which state the content pack will not work with anything less than 6.5.  Unfortunately, that information is not specified in the ASSETS section of the page (Bottom) where a customer would download the content.  Currently, version 5.5 and 6.0 are the only versions to be called out.

I have a customer that is air gapped and must download the content; however, they are on a earlier version of XSOAR and it would appear this content will not load into their system.

## Screenshots

![limites](https://user-images.githubusercontent.com/81991868/151852404-1f3697cc-1bd2-470d-917b-a8f59e5fa0eb.PNG)
![minimum](https://user-images.githubusercontent.com/81991868/151852420-b383332e-fef3-436d-963c-e31c35028493.PNG)

## Suggested fix

Maintain the actual content pack requirements.  Some customers are still on 6.1 or earlier, and it looks like this content will not work for them!

**Comment by Itay4** [comment]
hi @PaulBartruff 

thanks for reaching out

those integrations are not from version 6.5, the references that you highlight are bug fixes in those integrations for features that are implemented in the backend and are available from version 6.5

we do mention for every pack if it is available only from specific server version, not just 5.5 or 6.0

as you can see, the marketplace packs asset is for 6.0 and later, so it will work for users on 6.1 as well - some items might be missed but as i mentioned we document those

respectfully im going to close this issue as this seems to be a misunderstanding, please feel free to reach out if you have any further questions
