### ISSUE TITLE
Issue with "Microsoft Cloud App Security" in @site/docs/reference/integrations/microsoft-cloud-app-security.md

### ISSUE THREAD

**Issue by jpeng19** [demisto/content-docs#974]
## Describe the problem

* Page: [Microsoft Cloud App Security](https://xsoar.pan.dev/docs/reference/integrations/microsoft-cloud-app-security)
* Source: https://github.com/demisto/content/blob/master//Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md

Need help getting 'User's key to access the API.' I did not see the steps do this in the documentation.
Please list the steps, other than link to Microsoft docs, as MS docs have different links/paths in them, no sure which one to follow.

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by ChanochShayner** [comment]
duplicate of https://github.com/demisto/content-docs/issues/963
