### ISSUE TITLE
Issue with "Cortex XSOAR IDE" in @site/docs/concepts/xsoar-ide.md

### ISSUE THREAD

**Issue by gomesian** [demisto/content-docs#980]
## Describe the problem

* Page: [Cortex XSOAR IDE](https://xsoar.pan.dev/docs/concepts/xsoar-ide)
* Source: https://github.com/demisto/content-docs/tree/master/docs/concepts/xsoar-ide.md

we don't seam to have anywhere the IDE keybord shortcuts listed?

e.g. comment multiple lines:
On a mac - CMD + /
On Windows, CTRL + /

## Suggested fix

Add to this page or create a page for XSOAR keyboard IDE shortcuts?

**Comment by gomesian** [comment]
We could also add here I guess also:
https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-1/cortex-xsoar-admin/cortex-xsoar-overview/keyboard-shortcuts.html

**Comment by ostolero** [comment]
Documentation was updated with useful keyboard shortcuts.
The updated page - [Cortex XSOAR IDE](https://xsoar.pan.dev/docs/concepts/xsoar-ide)
