### ISSUE TITLE
Issue with "SAML 2.0" in @site/docs/reference/integrations/saml-20.md

### ISSUE THREAD

**Issue by deese** [demisto/content-docs#993]
## Describe the problem

* Page: [SAML 2.0](https://xsoar.pan.dev/docs/reference/integrations/saml-20)
* Source: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/integrations/saml_2.md

Today I was working on the SAML implementation and I had an issue with the private key. After some troubleshooting I ended up reading the source code of the X509 module for go and I found out the issue. 

It seems that the type of private key required for this module is a PKCS#1 and not a PKCS#8. Modern versions of OpenSSL uses PKCS#8 (adding the OID to the private key, more info: https://stackoverflow.com/a/1726728) 

The solution is pretty easy but it was a pain to find out the issue. 

Not for me but for other customers, It would be nice if the documentation can be updated with this specific information as a lot of people will use new versions of OpenSSL. 

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by MosheEichler** [comment]
@deese did you mean something like this?
![Screen Shot 2022-03-14 at 6 36 00](https://user-images.githubusercontent.com/78307768/158105808-2a71442c-02aa-46c8-ae4b-3d71d39bce7c.png)
