### ISSUE TITLE
Issue with "Slack v3" in @site/docs/reference/integrations/slack-v3.md

### ISSUE THREAD

**Issue by ali-sawyer** [demisto/content-docs#997]
## Describe the problem

* Page: [Slack v3](https://xsoar.pan.dev/docs/reference/integrations/slack-v3)
* Source: https://github.com/demisto/content/blob/master//Packs/Slack/Integrations/SlackV3/README.md

Request for improvement: Please list and add descriptions for all possible values of the `permitted_notifications` parameter. The biggest issue is I am aware of at least one possible value that is undocumented, `externalFormSubmit`. It is required to use Slack v3 for Data Collection tasks. Most of the other values are obvious but not all of them, e.g., we should clarify the difference between `incidentChanged` and `incidentStatusChanged`. Please add a brief description for all of them. 

## Screenshots

Please document these values including any that are missing from the integration, like `externalFormSubmit`:

<img width="751" alt="Screen Shot 2022-02-18 at 11 32 12 AM" src="https://user-images.githubusercontent.com/91506078/154742101-ccf6fad9-a714-44b9-854e-2b57530a0e59.png">

## Environment
 - OS: macOS
 - Browser: Chrome
 - Browser Version: 98.0.4758.80

## Suggested fix

In the doc, list and add a brief description for each value listed under `permitted_notifications`, plus the extra one `externalFormSubmit`.

**Comment by ali-sawyer** [comment]
Found one more missing value for `permitted_notifications` that needs added to the documentation: `failedFetchIncidents`

**Comment by MosheEichler** [comment]
Closing the issue by [this](https://github.com/demisto/content/pull/18196) pr
